### ISSUE TITLE
 Error:Execution failed for task ':react-native-fbads:processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by Liujiaohan** [callstack/react-native-fbads#100]
after I run react-native run-android
I can't get rid of this error

> Error:Execution failed for task ':react-native-fbads:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by Trancever** [comment]
@Liujiaohan Hi, can you provide more informations? Steps to reproduction or maybe small repository reproducing an issue?

**Comment by erandagan** [comment]
Stale, closing
