### ISSUE TITLE
Build fails with newest Audience Network SDK 4.99.0

### ISSUE THREAD

**Issue by perrosnk** [callstack/react-native-fbads#101]
Build fails on Android (and probably on iOS as well but haven't tested) because there are some breaking changes on native ad: https://developers.facebook.com/docs/audience-network/changelog-android#4_99_0

**Comment by DollieExloo** [comment]
I have the same problem. Did you already have a fix for it?

**Comment by perrosnk** [comment]
Unfortunately not, although you can specify a version up to 4.28.0 and it works fine apart from native ads on Android. Do native ads on android work in your case @DollieExloo ?

**Comment by DollieExloo** [comment]
I'll wait with adding Facebook ads for a bit longer then I guess. And no sorry haven't tried Android yet @perrosnk

**Comment by perrosnk** [comment]
@DollieExloo Native ads work both on iOS and Android using the v.4.28.0 instead of the newest 4.99.0. The problem with android was something [else](https://github.com/callstack/react-native-fbads/issues/99#issuecomment-400338824)

**Comment by erandagan** [comment]
The newest version of this library works with 4.99+
