### ISSUE TITLE
Cant display native ads on android

### ISSUE THREAD

**Issue by littlehome-eugene** [callstack/react-native-fbads#104]
NativeAdsManager.isValid is false and ads is not showing.
I wonder why isValid is false and not changing

Are you testing on a REAL device with the FB app installed and logged in with the manager account of FB? : YES

I see the status of placement in the admin as `running`

I also changed `if (deviceHashedId.equals("current")) {` as well..

**Comment by zensuke** [comment]
me too

**Comment by zensuke** [comment]
sorry. android 4.4 kitkat is app stopping isuue is multiDexEnabled problem.
but android 4.4 - 7 Cant display native ads.

**Comment by erandagan** [comment]
This issue refers to an old version of this package. Native ads are working as expected, if you're still having trouble feel free to open a new issue with repro.
