### ISSUE TITLE
Build Failed : Property 'title' not found on object of type 'FBNativeAd'

### ISSUE THREAD

**Issue by AaronBentley** [callstack/react-native-fbads#105]
Hello everyone 👋

I'm looking to implement Facebook Ads into my application, I have followed the install guides and installed the SDKs as instructed but now cannot build my project.

I am receiving the following 2 errors in Xcode:
- "Property 'title' not found on object of type 'FBNativeAd *'"
- "No visible @interface for 'FBNativeAd' declares the selector 'registerViewForInteraction:withViewController:'"

I've searched for a resolution to this but to no avail - for info I'm currently using:
- React Native: 0.55.2
- React Native fbads: 4.2.3
- FacebookSDK 4.34.0
- FBAudienceNetwork 4.99.1

Appreciate any links, ideas or suggestions as to how I can resolve this.

Thanks in advance,

Aaron 👍

**Comment by Trancever** [comment]
Hi @AaronBentley . Could you try with FBAudienceNetwork v4.28.x or earlier? Recently facebook released new version with breaking changes and we don't support it. 
We are working on new version of this library which will fix existing bugs and maybe support the new sdk.

**Comment by AaronBentley** [comment]
Thank you @Trancever, I appreciate your swift response 👏

I have switched to version 4.28.1 and can confirm things are playing nicely together now.

Thanks again and closing this issue.
