### ISSUE TITLE
CTKBannerView was not found in the UIManager

### ISSUE THREAD

**Issue by colinulin** [callstack/react-native-fbads#107]
Followed all of the instructions and have FBSDK working for Facebook login without any issues. I build my app and suddenly get a "CTKBannerView was not found in the UIManager" error. My hunch is that it's because this guide seems a bit outdated (you no longer drag any .framework files to link binaries in XCode for the main FBSDK). Is this module still package still usable with the current versions of FBSDK and React-Native?

![simulator screen shot - iphone 6 - 2018-08-26 at 22 38 23](https://user-images.githubusercontent.com/34677247/44632767-c15ff700-a980-11e8-86b7-167389c5edff.png)

Setup:
├── @firebase/app-types@0.3.2
├── adm-zip@0.4.11
├── fbjs@0.8.17
├── UNMET PEER DEPENDENCY firebase@5.4.1
├── geofire@4.1.2
├── lodash@4.17.10
├── plist@3.0.1
├── prop-types@15.6.2
├── UNMET PEER DEPENDENCY react@16.4.2
├── react-native@0.56.0
├── react-native-communications@2.2.1
├── react-native-fbads@4.2.3
├── react-native-fbsdk@0.7.0
├── react-native-firebase@4.3.8
├── react-native-google-places-autocomplete@1.3.9
├── react-native-map-link@2.1.0
├── react-native-router-flux@4.0.1
├── react-native-sentry@0.39.0
├── react-native-slider@0.11.0
├── react-native-vector-icons@5.0.0
├── react-redux@5.0.7
├── redux@4.0.0
├── redux-thunk@2.3.0
└── xcode@1.0.0

npm: 6.4.0-next.0
node: v8.10.0

**Comment by Im-Goutham** [comment]
Getting sample error for me . Please give a solution for it .

**Comment by erandagan** [comment]
This question is referring to an outdated version of this package (react-native-fbads@4.2.3)
Please upgrade and see if the issue persists.
There's some active work going on to stabilize the code and the docs, contributions are welcome.

**Comment by kaushalmarakana** [comment]
You need to import some java statements for load facebook ads packages. 
#205 (Check this)
