### ISSUE TITLE
Unable to find a matching configuration of project :react-native-fbads - Android

### ISSUE THREAD

**Issue by leo7r** [callstack/react-native-fbads#108]
I'm getting this error when trying to compile for Android (debug and release builds):

```
* What went wrong:
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fbads: None of the consumable configurations have attributes.
```

I am able to compile ok in iOs. What can I do to solve this? I have tried unlinking and linking again, uninstalling and installing again library but no luck.

React native: 0.44
React: 16.0.0-alpha.6
react-native-fbads: 4.2.3

**Comment by bernardojm91** [comment]
I have the same issue D:

**Comment by leo7r** [comment]
It was a duplicate definition in `android/settings.graddle`

**Comment by akhzarna** [comment]
I have the same issue

**Comment by akhzarna** [comment]
> I'm getting this error when trying to compile for Android (debug and release builds):
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
>    > Could not resolve project :react-native-fbads.
>      Required by:
>          project :app
>       > Unable to find a matching configuration of project :react-native-fbads: None of the consumable configurations have attributes.
> ```
> 
> I am able to compile ok in iOs. What can I do to solve this? I have tried unlinking and linking again, uninstalling and installing again library but no luck.
> 
> React native: 0.44
> React: 16.0.0-alpha.6
> react-native-fbads: 4.2.3

I have the same issue, have you resolved the issue ?
