### ISSUE TITLE
This Package Completely Broke my Project

### ISSUE THREAD

**Issue by ameshkin** [callstack/react-native-fbads#110]
I get a lot of errors like this. I've tried many things I have found online. Even reverted back in GIT. I still can't fix it.

jest-haste-map: @providesModule naming collision:
  Duplicate module name: String.prototype.es6

**Comment by erandagan** [comment]
If you reverted back on git, ran `npm` or `yarn` and still having issues, this can't be related to this package.

Try removing your node_modules and running a clean installation according to the lockfile.
