### ISSUE TITLE
[WIP] iOS - issue while archive

### ISSUE THREAD

**Issue by Nits7029** [callstack/react-native-fbads#112]
Hello,

I have integrated fbads package using pods, and am getting an error while archiving build, in debug mode its working fine, here is attached error screenshot

![screen shot 2018-09-17 at 6 38 58 pm](https://user-images.githubusercontent.com/9457796/45624974-66b24a80-baa9-11e8-9c81-142b06081926.png)

it says libReactNativeAdsFacebook.a file not found. Please help me ASAP to sort it out this issue.

Thanks

**Comment by Nits7029** [comment]
FYI: I have implemented latest package from master branch

**Comment by EasonLex** [comment]
I got the same issue. Any ideals?

**Comment by leo7r** [comment]
Same here

**Comment by EasonLex** [comment]
It seems ReactNativeAdsFacebook didn't generate .a file when release. The easy way to reproduce this issue is change Xcode run from debug to release. And you will find there is no libReactNativeAdsFacebook.a in Release-iphoneos folder.

**Comment by Suraj-Tiwari** [comment]
@Trancever Ok I'll fix it tonight

**Comment by Suraj-Tiwari** [comment]
Fixed [https://github.com/callstack/react-native-fbads/pull/113](https://github.com/callstack/react-native-fbads/pull/113)

**Comment by Nits7029** [comment]
@Suraj-Tiwari  is your changes merged and live?

**Comment by Trancever** [comment]
Released version 5.0.1 with @Suraj-Tiwari fix.

**Comment by leo7r** [comment]
@Nits7029 last version fixed the problem for you? I can't get it to work on my side

**Comment by Suraj-Tiwari** [comment]
Ok, so some of you will still face the issue, new issue is related to cli itself, react-native isn't linking correctly. Do this and you're ready to go

![screenshot at sep 20 05-19-48](https://user-images.githubusercontent.com/22210490/45787889-1b5c8f80-bc95-11e8-908f-fd1f99dff2bb.png)

**Comment by EasonLex** [comment]
@Suraj-Tiwari Thanks for your great help, and seems add Target Dependencies works fine for this issue. After add target dependencies, .a file generated, but I still got build fail with bitcode error. I try to set Deployment Target from 11.4 to 9.0(what my project set), and it worked perfectly.

**Comment by kyungjoongo** [comment]
> @Suraj-Tiwari Thanks for your great help, and seems add Target Dependencies works fine for this issue. After add target dependencies, .a file generated, but I still got build fail with bitcode error. I try to set Deployment Target from 11.4 to 9.0(what my project set), and it worked perfectly.

how to add target dependency?

**Comment by Suraj-Tiwari** [comment]
@kyungjoongo see this image https://github.com/callstack/react-native-fbads/issues/112#issuecomment-422994854
