### ISSUE TITLE
performance issue with MediaView component

### ISSUE THREAD

**Issue by Nits7029** [callstack/react-native-fbads#114]
while using MediaView component, it makes app performance slower and app hangs on scroll.

@Trancever  Whats the solution? Thanks

**Comment by Nits7029** [comment]
and for android release app, read ads are not showing so what is that issue? How i can debug it.

in release app, am commenting `addTestDevice` line

**Comment by Suraj-Tiwari** [comment]
@Nits7029 please go with Facebook documentation, and media view don't have any effect one performance. Bad implementation have a look [here](https://developers.facebook.com/docs/audience-network/testing)

@Trancever thats a bad implementation

**Comment by Nits7029** [comment]
@Suraj-Tiwari  what to look into the link you have given? How that's bad implementation?

**Comment by Nits7029** [comment]
its clear that when i remove MediaView component from native ads, it works smoothly

**Comment by Suraj-Tiwari** [comment]
you need approval to make it work in release and (not sure >) user must have facebook app in their phone.

**Comment by Nits7029** [comment]
yes its approved and i know about facebook app installed with the same login as FB business account

**Comment by Nits7029** [comment]
what happened is, native ads displayed about 15 min and then automatically got the test ads, interstitial ads are showing fine

**Comment by Suraj-Tiwari** [comment]
Try to set ad limit to 1 default 10

**Comment by Nits7029** [comment]
I am displaying 4 to 5 native ads so what's the best approach?

per ad, new adManager?

or single adManager instance with 4/5 limit set?

**Comment by Suraj-Tiwari** [comment]
if you are showing all ads in single component then request them in single. 
```js 
const adsManager = new NativeAdsManager(placementId, numberOfAdsToRequest);
```

for one at a time  simply do 
```js
const adsManager = new NativeAdsManager(placementId, 1);
``` 
if nothing passed, default will be 10.
