### ISSUE TITLE
[Feature] Supporting Native Banner Ads (SDK 4.99+)

### ISSUE THREAD

**Issue by erandagan** [callstack/react-native-fbads#122]
With SDK 4.99, Facebook added Native Banner Ads to their SDK and stopped supporting the display of regular Native Ads that don't include a `MediaView`.

Moreover, Facebook no longer approves Native Ads that don't include a MediaView and some other required content, as described in [their SDK upgrade guide.](https://developers.facebook.com/docs/audience-network/upgrade_guide_android_4_99)

Comparison between ad types:
Banner:
https://scontent.ftlv1-1.fna.fbcdn.net/v/t39.2365-6/29795681_2120086391611419_6799855144298086400_n.png?_nc_cat=104&oh=1a1fe029ee5dc27fb5a56f5a6c8b16a4&oe=5C50A5E2
([Facebook docs](https://developers.facebook.com/docs/audience-network/android-native-banner))

Media:
https://scontent.ftlv1-1.fna.fbcdn.net/v/t39.2365-6/15216307_1230458850326591_6545403358784520192_n.png?_nc_cat=106&oh=6ba787d0fe601c001d64cb6d4c34800b&oe=5C5D485D
([Facebook docs](https://developers.facebook.com/docs/audience-network/android-native))

From my testing, it seems like banner ads are working fine when the placement id is configured accordingly. However, we might have to make a few small changes:

- Stop force rendering `MediaView` components [here](https://github.com/callstack/react-native-fbads/blob/master/withNativeAd.js#L186) as these are required only for Native Ads, and not for Native Banner Ads.
- Point to facebook's requirements in the documentation

**Comment by Suraj-Tiwari** [comment]
@erandagan  if removed this native banner ads will crash 
https://github.com/callstack/react-native-fbads/blob/16ce3caadbe70d4cdd202af96ab51e09636e1db0/withNativeAd.js#L186

Media View Component is required by native sdk this was the only fastest way to catch up. if no media view is provided to native component this is going to crash. Or Touchables will not work. 

and facebook will approve this. 

If Media and Adicon view is included those includes will not work. SDK render only first component so those will not render.

https://github.com/callstack/react-native-fbads/blob/16ce3caadbe70d4cdd202af96ab51e09636e1db0/android/app/src/main/java/suraj/tiwari/reactnativefbads/NativeAdManager.java#L175

If using `NativeBannerAd` this is going to be a whole new function and bunch of files with no major use.

If still a dedicated component is needed we can take this to specific solution.

**Comment by erandagan** [comment]
I'm simply wondering if that's the right way to go here as we're kinda working against Facebook's SDK by treating both Native Media and Native Banner ads as the same, while Facebook's own SDK does implement them differently (which I suppose is for a good reason)

This is for discussion, of course.

**Comment by Suraj-Tiwari** [comment]
Obviously your point does make sense the only difference i found i nativead and native banner ad is 
the function which add touch event to all the assets within the ad. 
In `nativeAd` sdk require media component
in `nativeBannerAd` sdk doesn't require media component
that's the only difference i found within the code. 

And if you check native banner carefully (or add media component) it does have media data. all facebook decided to do is go without it in `nativeBannerAd` by removing 'Media' component requirement

This is the reason according to my investigation in the past

If you still think, we need a component for it. I'll do it, but later as I'll be busy for 2 weeks

**Comment by erandagan** [comment]
Sounds good. If we continue using the current implementation I think it's just important to keep in mind some people use the Native Banner functionality, just in case Facebook decides to introduce more differences between the two in future versions.

Another point - I think we should consider allowing users of this package to style the `AdChoicesView` that is included within `withNativeAd`.

Use case - when displaying a native ad within a `View` that has `elevation > 0` (or `zIndex` for that matter), the default `AdChoicesView` disappears as it's rendered behind the container.

We can approach this in 2 ways:
- Let everyone include <AdChoicesView/> and customize it as they wish, rather than including it ourselves. This is the most flexible approach.
- Simply allow passing a `adChoicesStyle` prop to all components wrapped in `withNativeAd` - this does not introduce breaking changes and is simple to implement.

Thoughts?
I can submit a PR for that

**Comment by erandagan** [comment]
#130 
Closing

**Comment by hend-elsahli** [comment]
any progress on supporting Native-Banner-Ads ?
