### ISSUE TITLE
[Discussion] Consider TS Migration

### ISSUE THREAD

**Issue by erandagan** [callstack/react-native-fbads#128]
Main arguments from the Expo team
https://github.com/expo/expo/issues/2164

I'm aware callstack generally use Flow for their typings, but it feels like TS would make it easier for contributors (including myself) to jump in.

We have very few JS files so migrating should be easy.

Thoughts?
@Suraj-Tiwari @Trancever

**Comment by Suraj-Tiwari** [comment]
No issue for me, TS makes project management easy.

**Comment by Trancever** [comment]
How about approach we have in `react-native-paper`? We use flow but we have also typings for typescript. Check this (PR)[https://github.com/callstack/react-native-paper/pull/561] and let me know what you think.

**Comment by Trancever** [comment]
@erandagan @Suraj-Tiwari I know it might be really hard and painful to keep both typings in sync but this project does not contain a lot of js files so we should try to maintain both of them. Let's for now switch to typescript and make the library stable. Once it's done we will think about maintaining flow typings also. Is this plan ok for you?

**Comment by Suraj-Tiwari** [comment]
Looks good to me

**Comment by Suraj-Tiwari** [comment]
Please Make it on beta branch and keep pushing so i can work on same..

**Comment by erandagan** [comment]
@Suraj-Tiwari I don't have permissions for that.
The code is under my fork on `migrate-to-typescript` branch.

The major work is done, I could use some help in testing and fixing the last typescript errors in `withNativeAd`.

**Comment by Suraj-Tiwari** [comment]
Please push all untested code to beta branch, we'll test from there and merge it to master after testing.

**Comment by Trancever** [comment]
@erandagan I see you are actively working on making this project better. Would you like to be in a core team and have direct access to repo?

**Comment by erandagan** [comment]
@Trancever Yes, that sounds good. Once I have the permissions I'll push the typescript branch to the main repo so we can test it and fix the last TypeScript errors, most of which are related to the `clickableChildrenNodeHandles` member in `withNativeAd`

**Comment by Trancever** [comment]
@erandagan Sent an invitation.

**Comment by erandagan** [comment]
@Suraj-Tiwari The branch is now available in the main repo, feel free to make any changes :)

**Comment by Trancever** [comment]
@erandagan Could you also set up running typescript checks on CI?

**Comment by erandagan** [comment]
@Trancever good idea, I hope I'll get to it this Friday.
