### ISSUE TITLE
How to load ads in JSON format

### ISSUE THREAD

**Issue by leksyib** [callstack/react-native-fbads#129]
Thank Y'all for this amazing project, It works fine. I just wanted to ask if I can load native ads in JSON format so I can render it among the content that I'm rendering in my app. Thanks!

**Comment by leksyib** [comment]
@Suraj-Tiwari Thanks for your response! So how do you suggest I render the ads alongside a flatlist component, and the ads stay inside the flatlist?

**Comment by Suraj-Tiwari** [comment]
Use logic in list item, and render native ad in between of them

Easiest workaround is

// put condition for every n number of item
<view/>
// native ad
// list item
<view/>

**Comment by leksyib** [comment]
@Suraj-Tiwari  Thanks! That's it.
