### ISSUE TITLE
Blurred Native ads

### ISSUE THREAD

**Issue by yyohanes** [callstack/react-native-fbads#132]
Hi there, 

I am getting blurred ads with the latest version `5.0.1`.
![20181010_170941](https://user-images.githubusercontent.com/661080/46729463-9f5fd100-ccaf-11e8-819c-06e70ceb963c.jpg)

Wondering if this is a known issue?

**Comment by Suraj-Tiwari** [comment]
Yup this is known and we already have a discussion going on with Facebook
about this issue, because something in Facebook Audience SDK is causing
this issue.

**Comment by yohanes1989** [comment]
Do you have suggestion to workaround this maybe?

**Comment by Suraj-Tiwari** [comment]
According to the Facebook team that is working fine there side, they wasn't
able to reproduce the error, something else is causing issue. We are still
working on it to resolve the issue

**Comment by yohanes1989** [comment]
Right. Thanks. I'll try to debug as well and see if I find anything.

**Comment by erandagan** [comment]
@Suraj-Tiwari Can this be related by any chance to the empty MediaView in withNativeAd? 
Just guessing here, but maybe it's worth checking without it and seeing if the problem persists.

**Comment by Suraj-Tiwari** [comment]
@erandagan me and one of my fellow developer check all possible scenarios, issue isn't with empty media view, as code is working fine with ios, issue is with android sdk (current unetest senario), facebook team is working on it to trace the issue.

**Comment by Jobeso** [comment]
Are there any updates on this because this makes the facebook ads not usable on android?

**Comment by HolaMan** [comment]
It's a very serious and blocking issue.
Is there anyway to push or track the facebook progress?

The issue directly affect the ads revenue which is a blocking issue from my view point !

**Comment by MiracleDeveloper** [comment]
++
We have suffered the same issues.
Any other suggestion or workaround?

**Comment by erandagan** [comment]
Unfortunately there's no cooperation from Facebook's side on some critical issues related to RN compatibility. It seems like we can only wait until they provide official support.

**Comment by Suraj-Tiwari** [comment]
i tried to file issue and contact them with no proper response from them so
i think they won't resolve this issue. atleast for now

**Comment by MiracleDeveloper** [comment]
RN team just closed the issue, we need to find other channels or ways to report the issue.

**Comment by erandagan** [comment]
It's not the RN's team responsibility, but Audience Network's. They don't
support
RN officially at the moment.

**Comment by HolaMan** [comment]
No.
We have reported to Audience Network team but no concrete progress for weeks.
Actually we don't know how to make any progress on this issue.

**Comment by HolaMan** [comment]
We submit the issue here
https://developers.facebook.com/support/bugs/230915631133114/?resurrect_cookie=1&_rdr

**Comment by freakyfriday** [comment]
Any news on this issue? Facebook have closed the issue as they can't replicate it.

**Comment by raphaeleidus** [comment]
I think I have an idea on the implementation problem that might be causing this

In reviewing the docs for the audience SDK I noticed this:

> add a container for your Native Ad. The container should be a `com.facebook.ads.NativeAdLayout` which is a wrapper on top of a FrameLayout with some extra functionality that enabled us to render a native Ad Reporting Flow on top of the ad.

In reviewing the source for this library there is no reference to `NativeAdLayout`. I think if we can start using it it may resolve a number of problems (on android at least)

**Comment by Suraj-Tiwari** [comment]
Thanks for your investigation, I'm looking into it.

**Comment by yohanes1989** [comment]
@raphaeleidus Tried rendering the ads natively on Android side by wrapping with `NativeAdLayout` and still no bueno. Still getting the blurred image.

**Comment by Suraj-Tiwari** [comment]
Could be the version issue, which version you tried to test?
and what about native ui.?

**Comment by freakyfriday** [comment]
For the Android devs are there any clues in the expo implementation of FacebookAds?

https://github.com/expo/expo/blob/master/packages/expo-ads-facebook/android/src/main/java/expo/modules/ads/facebook/NativeAdLayoutManager.java

**Comment by seomaz** [comment]
Any updates ?

**Comment by seomaz** [comment]
@Suraj-Tiwari   It could be related ? https://developers.facebook.com/docs/audience-network/android-layout-guideline

**Comment by seomaz** [comment]
@Suraj-Tiwari  To avoid this, is there any way to request only video ads and carousel?

**Comment by Suraj-Tiwari** [comment]
Not sure, Facebook supports excluding video content, i think we can archive
this by tweaking parameter of Ads pricing.

**Comment by hend-elsahli** [comment]
Anything new ?

**Comment by TMaszko** [comment]
Please check out v7 available now ! :)  if it isn't fixed then I'll reopen it.

**Comment by srikantOfficial** [comment]
Same Problem. Image Blur issues is continued.

Google Native Ads is working fine but in facebook its not working
