### ISSUE TITLE
dyld: Library not loaded libios-sdk_ads_src_FBAudienceNetwork_FBAudienceNetworkRelease.dylib

### ISSUE THREAD

**Issue by dannyyaou** [callstack/react-native-fbads#133]
**Version**

"react-native": "^0.40.0"
"react-native-fbads": "^5.0.1",

**Problem**

After building successfully, my app can not really start with this error log:

dyld: Library not loaded: @rpath/libios-sdk_ads_src_FBAudienceNetwork_FBAudienceNetworkRelease.dylib
  Referenced from: /Users/USERNAME/Library/Developer/CoreSimulator/Devices/1FC8A1EA-C331-4E58-A4DF-39D104FF6E5F/data/Containers/Bundle/Application/6636B239-E502-46AD-8E4F-FE75DD76198F/APPNAME.app/APPNAME
  Reason: image not found
(lldb) 

If anyone met or know how to solve it, please let me know, thanks!

**Comment by Suraj-Tiwari** [comment]
Using pods? and latest xcode?

**Comment by dannyyaou** [comment]
I don't use pods
Xcode version is Version 10.0 (10A255)

**Comment by Suraj-Tiwari** [comment]
Please use pods without it its really complicated to make it worked
correctly

**Comment by dannyyaou** [comment]
Thanks, I'll try
