### ISSUE TITLE
[Feature] Make Custom Views Triggerable

### ISSUE THREAD

**Issue by erandagan** [callstack/react-native-fbads#135]
Currently, `TriggerableView` only supports a single hardcoded child which is a `Text` node. This prevents users from including custom components in the native ad, most noticeably a custom Button component for the ad's click action (eg. *Install Now* button).

Also, users may already have their own set of components in place (eg. a `<MyText>` component with styling that matches their app, or a `<MyButton>` component) which we want them to be able to include within the Native Ad component.

As for the implementation, we can approach this in a few ways:
- Export the `TriggerableView.Context` - this will enable users to access `register` and `unregister` and bind their own view refs. This isn't very ergonomic, but will work out of the box.

- Pass `register` and `unregister` automatically to the user's top level Native Ad component. This is pretty much the same as the previous option, but a bit nicer to use.

- Ideally, `TriggerableView` would just support passing any custom children and will automatically bind the top level ones. Eg `<TriggerableView> <MyButton/> </TriggerableView>`

Options 1 and 2 both require the user to manage the register/unregister lifecycle in a similar way to how the internal components work (keeping the previous ref as a member), which can be error-prone unless we provide a nice mechanism here (eg. `register(ref, 'someId')` will automatically `unregister` the previous ref under the same id, if any)

The third option seems to be the best one usage-wise, I'm just not entirely sure if we can get the children `ref` appropriately in that case without resorting to some dirty tricks.

**Comment by Suraj-Tiwari** [comment]
I have tried that, having nested triggerable component is creating issue with native code, as native code have to register view id to make it trigger specific event.

**Comment by erandagan** [comment]
Nesting of Triggerables inside Triggerables (if I understand your reply correctly) isn't required, just having something like this:

```js
<Triggerable>
  <View style={...}> <-- This view is registered natively
     <Text>Hello!</Text>
  </View>
</Triggerable>
```

**Comment by Suraj-Tiwari** [comment]
with this code ad will show but won't take trigger event on text tested on `4.99.1`

**Comment by Suraj-Tiwari** [comment]
and i'm talking about nesting `View` inside `Triggerable` as `Triggerable` is also a view

**Comment by erandagan** [comment]
So you're saying that the FB SDK won't fire clicks related to React managed ViewGroups?

**Comment by Suraj-Tiwari** [comment]
I made it like the way you said, it wasn't working. Nesting text directly inside Triggerable worked.

**Comment by erandagan** [comment]
@Suraj-Tiwari Hmmm, I don't think there should be a specific issue here as the native iOS SDK does allow registering custom (iOS native) views, so we should be able to bind the container view in one way or another

**Comment by Suraj-Tiwari** [comment]
issue was occurring in this function with android. and making 2 different method for a component is a dirty practice. While debugging it was able to register the triggerable but wasn't initiating.  

https://github.com/callstack/react-native-fbads/blob/2810b277a7742a8d3a280c62e3a76b8871daa18f/android/app/src/main/java/suraj/tiwari/reactnativefbads/NativeAdManager.java#L147

**Comment by Suraj-Tiwari** [comment]
As mostly i'm tight on schedules and i was working alone. But currently you are working too, I might me able to trace the exact issue.

**Comment by erandagan** [comment]
Great, if you find anything interesting feel free to share it in this issue

**Comment by Suraj-Tiwari** [comment]
Yeah sure.

**Comment by erandagan** [comment]
@Suraj-Tiwari did you have the chance to look into this?

**Comment by Suraj-Tiwari** [comment]
@erandagan I'll busy at my office for some days. I'll check after some days.

**Comment by TMaszko** [comment]
We haven't received more info about this proposal recently so I'll close it for now.
