### ISSUE TITLE
[Admob Mediation] How to work with Mediation of admob?

### ISSUE THREAD

**Issue by ducpt2** [callstack/react-native-fbads#137]
I have a question, does we need to do anything more to work with Mediation of admob?

Thank a lots.

**Comment by erandagan** [comment]
As of now, AdMob mediation isn't supported by this library. I don't think it will be added, as it requires a tight native integration and essentially requires another library.

**Comment by zoobibackups** [comment]
> I have a question, does we need to do anything more to work with Mediation of admob?
> 
> Thank a lots.

Any solution??
