### ISSUE TITLE
[WIP] Update Example

### ISSUE THREAD

**Issue by erandagan** [callstack/react-native-fbads#147]
The example project in this repo is outdated and requires some changes in order to work with the current version of this library. 

Any contributions would be appreciated.

**Comment by Suraj-Tiwari** [comment]
I'm working on it

**Comment by erandagan** [comment]
Awesome :)

**Comment by erandagan** [comment]
Hey @Suraj-Tiwari, did you have the chance to proceed with this? Thanks!

**Comment by Suraj-Tiwari** [comment]
I'm working of frequent crashes In some implementation.
Sometime it randomly crash. Still trying to trace the reason.

**Comment by erandagan** [comment]
@Suraj-Tiwari Possibly related to #170?
