### ISSUE TITLE
AdIconView and MediaView are very laggy in Flatlist.(iOS)

### ISSUE THREAD

**Issue by a26364177** [callstack/react-native-fbads#149]
[AdIconView in Flatlist](https://youtu.be/oGpZvFLrVB8)
[Without AdIconView](https://youtu.be/Lajc0tTLMdg)

It works very good, without AdIconView in Flatlist.
Facebook Audience Network SDK 5.0.2
My react-native-fbads lib use Github version.

```
const styles = StyleSheet.create({
  container: {
    marginVertical: 5,
    marginHorizontal: 10,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center'
  },
  img: {
    width: 92,
    height: 52,
    ...BackgroundColor.ImageBG
  },
  text: {
    fontSize: 13,
    lineHeight: 18,
    ...FontColors.Main,
    marginHorizontal: 8,
    flex: 1
  },
  callActionText: {
    fontSize: 10,
    paddingVertical: 2,
    paddingHorizontal: 5,
    ...FontColors.Main,
    borderRadius: 8,
    ...BorderColor.Main,
    borderWidth: 1
  },
  adText: {
    fontSize: 10,
    ...FontColors.Third,
    position: 'absolute',
    right: 3,
    bottom: 3,
    borderRadius: 5,
    paddingHorizontal: 5,
    overflow: 'hidden',
    ...BackgroundColor.SearchPlaylistTime
  }
})

let adsManager = new NativeAdsManager(FB_NATIVE_ADS_BANNER_ID)
let FBNativeAdsRowView = ({style, nativeAd}) => {
  return (
    <View style={[styles.container, style]}>
      <AdChoicesView style={{ position: 'absolute', right: -10, top: -5 }} location={'topRight'} expandable />
      <View style={styles.img}>
        <AdIconView style={styles.img} /> // without this works fine either
        <TriggerableView style={styles.adText} numberOfLines={1}>
          {nativeAd.sponsoredTranslation}
        </TriggerableView>
      </View>
      <TriggerableView style={styles.text} numberOfLines={3}>
        {nativeAd.advertiserName + '\n' + nativeAd.socialContext}
      </TriggerableView>
      <TriggerableView style={styles.callActionText} numberOfLines={1}>
        {nativeAd.callToActionText}
      </TriggerableView>
    </View>
  )
}

let FBNativeAdsView = withNativeAd(FBNativeAdsRowView)

class FBNativeAdsRow extends React.Component {
  componentWillMount () {
    if (!adsManager.isValid) {
      adsManager = new NativeAdsManager(FB_NATIVE_ADS_BANNER_ID) // Facebook Native Ads Banner ID
    }
  }

  render () {
    return (
      <FBNativeAdsView
        onAdLoaded={() => {
        }}
        adsManager={adsManager}
      />
    )
  }
}
```

**Comment by Suraj-Tiwari** [comment]
Flatlist always have some issue if list item have multiple Triggerable
component.
Didn't tested it with latest but was definetly an issue with older version.

Still i would like to see your implementation. With your Flatlist code.

**Comment by Jobeso** [comment]
I encounter the same problem with the latest npm release (not the beta version) on iOS. This still occures after refactoring the item to use only one TriggerableView. I think the mayor problem are video ads, for ads with images the performance works decent.
This even applies for only one ad in the whole flatlist.

**Comment by erandagan** [comment]
This actually happens even without media ads - simply having the AdIconView causes a performance issue. Maybe Facebook's touchable registration is somehow interfering with FlatList's gesture handling?

**Comment by Suraj-Tiwari** [comment]
Well Not with ads but during some work i found Flatlist have some issue
with literally any Touch event. Other than list item. In current version 🙄

**Comment by erandagan** [comment]
@a26364177 Could you pop up the React Native performance overlay to see if the FPS really does drop, or is it just the two touch systems interfering with one another, causing scrolling issues?

**Comment by a26364177** [comment]
[AdIconView in Debug Mode](https://youtu.be/E8d-gjTBOrM)

React Native: v0.57.0
Device: iOS 12.0 iPhone 6s Plus

```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 10
  }
})

const Playlist = ({
}) => {
    return (
      <FlatList
        style={styles.container}
        data={new Array(1000)}
        getItemLayout={(data, index) => (
          {length: 62, offset: 62 * index, index}
        )}
        keyExtractor={(item, index) => index.toString()}
        renderItem={({item, index}) => renderRow()
        }
      />
    )
  }
}

const renderRow = (index) => {
  let ad
  if (index % 50 === 0) {
    ad = (
      <FBNativeAdsRow />
    )
  }
  return (
    <View>
      {ad}
      <View style={{height: 62}}>
        <Text>{index}</Text>
      </View>
    </View>
  )
}
```

**Comment by erandagan** [comment]
It looks like both the UI and JS threads are choked here. I'll try to investigate further this weekend.

**Comment by dblazeski** [comment]
Had the same issue, wasn't able to track down why it happens. Can confirm MediaView is definitely laggy.
Temp fix is to apply `removeclippedsubviews={true}` on the [FlatList](https://facebook.github.io/react-native/docs/flatlist#removeclippedsubviews) component.

**Comment by blitzcrank** [comment]
Any progress on this issue? I have tried @dblazeski 's suggestion but `removeclippedsubviews={true}` doesn't work for me.

The entire main thread is locked due to `FBAdQualityViewabilityMeasurement overlappingRectsInView:targetRect` method being from a Timer (as seen in this thread: https://bugs.netnoc.eu/browse/TWOO-67864)

**Comment by hend-elsahli** [comment]
I can confirm this lagging issue ... and I guess it's because the suitable-format of native-ad that could be used without issues inside a scrollable-area is **Native Banner Ad** not  **Native Ad** ... which is not supported I think by the module

Native-Banner ads does not requires **MediaView**  inside the children tree to trigger the ad...

[(https://developers.facebook.com/docs/audience-network/guides/ad-formats/native)](url)

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it isn't fixed then I'll reopen it.
