### ISSUE TITLE
Native Ads are not Display in Android 

### ISSUE THREAD

**Issue by mahesh963** [callstack/react-native-fbads#150]
Hi, to everyone. I am using **react-native-fbads** in my project. I have followed the instructions and done the linking successfully.
Created the Component for Native Ads to use the custom styles in my ListView as a Record. I have generated the Placement Id for Native Ads. Even though my App is reviewed successfully and I got status as Ready to Publish in [https://developers.facebook.com](url) in developers console

### Current Behavior
-  Loading the Demo FB-Ads instead of Live Ads
- ![sample](https://user-images.githubusercontent.com/20550553/47776873-6698a200-dd19-11e8-9411-8576b387bc97.png)

### Expected Behavior

- How to get live Fb-Ads like the below screenshot?
![fbadssample](https://user-images.githubusercontent.com/20550553/47777016-c8590c00-dd19-11e8-9771-55d71e925fea.png)

- Please,Suggest me. How to resolve this?

**Comment by erandagan** [comment]
Hi there,
Could you please:
- Specify which version of the library you're using
- Attach a code sample of your usage

**Comment by Suraj-Tiwari** [comment]
@mahesh963 
Please confirm if you have removed `AdSettings.addTestDevice(AdSettings.currentDeviceHash);` and using a **production build on real device** and _facebook app on your real device isn't related to your developer account_  also make sure to execute this `AdSettings.clearTestDevices();` once.

**Comment by mahesh963** [comment]
hi @erandagan thanks for your reply

- I am using "react-native-fbads": "^5.0.1"
- Below is my **sample code** please check it once
```
import React, { Component } from 'react';
import { Text, View, Dimensions } from 'react-native';
import {
  withNativeAd,
  AdIconView,
  TriggerableView,
  MediaView,
  AdChoicesView,
} from 'react-native-fbads';
import styles from './../../styles/style.js'
var windowSize = Dimensions.get('window');
import { scale, moderateScale, verticalScale} from '@components/FontScaling/FontScaling.js';

class NativeAdView extends Component<Props> {
  render() {
    return (
      <View style={styles.NativeAds}>
        <View style={{flex:1,flexDirection:'row',marginTop:5}}>
          <View style={{flex:0.16,backgroundColor:'transparent'}}>
            <AdIconView style={{height: windowSize.width/9,
                width:windowSize.width/9,borderRadius:10,backgroundColor:'grey',alignSelf:'center',marginLeft:scale(6)}} />
          </View>
          <View style={{flex:0.84,backgroundColor:'transparent',flexDirection:'column'}}>
            <TriggerableView style={{flex:0.5,backgroundColor:'transparent'}}>
              <Text style={[styles.carouselHeadTxt,{marginRight:3}]}>
                  {this.props.nativeAd.headline}
              </Text>
            </TriggerableView>
            <TriggerableView style={{flex:0.5,backgroundColor:'transparent'}}>
              <Text style={{fontSize: scale(11.5),
                  lineHeight: 18,marginRight:3,
                  fontFamily: "GoogleSans-Regular",color:'#515365',marginTop:-1}}>
                {this.props.nativeAd.sponsoredTranslation}
              </Text>
            </TriggerableView>
          </View>
        </View>
        <TriggerableView style={{margin:scale(10)}}>
        <Text
          numberOfLines={6}
          style={[styles.messagE, {lineHeight:23,fontFamily:'GoogleSans-Regular', fontSize: scale(15)}]}>
          {this.props.nativeAd.linkDescription}
        </Text>
      </TriggerableView>
      <MediaView style={{width:windowSize.width,marginHorizontal:0,alignSelf:'center',height:windowSize.height*0.5}} />
        <View style={{ alignItems: 'center' }}>
          <TriggerableView
            style={{
              fontSize: scale(15),
              color: '#896fec',
              paddingVertical: 10,
              paddingHorizontal: 30,
              elevation: 3,
              borderTopWidth: 0,
              margin: 10,
              borderRadius: 6,
            }}
          >
            {this.props.nativeAd.callToActionText}
          </TriggerableView>
        </View>
      </View>
    );
  }
}

export default withNativeAd(NativeAdView);
```

- I have done a **NativeAdView**(`<NativeAdView />`)  as a Component and used in Another Screen as

```
import NativeAdView from '@components/FBNativeAds/NativeAdView';
import { NativeAdsManager, AdSettings } from 'react-native-fbads';
const adsManager = new NativeAdsManager('232245xxxxxxxxx_259163xxxxxxxxx',10);

<NativeAdView
          adsManager={adsManager}
          adChoicePosition="bottomRight" />
```

**Comment by a26364177** [comment]
1.Make sure you are using a physical device instead of a simulator.
2.Confirm that the Facebook app is installed on your test device.
3.Confirm that you (FB account) have used the enterprise management platform employee status currently set in the "Enterprise Management Platform Settings" to log in to the Facebook application from the test device.

**Comment by danrevah** [comment]
@a26364177 It seems like i'm having the same issue.. but I don't understand your third check: "Confirm that FB account have used the enterprise managment platform employee status currently set in the..?" .. wait what? what exactly do I need to check?

**Comment by a26364177** [comment]
@danrevah Your FB account need to add in Monetization Manager admin. And use Advertising debugging tool to get real test ad request in Monetization Manager.
Sorry for my poor english.

**Comment by danrevah** [comment]
Ok I did it but I can't see anything on my android app.. still no ad is shown

**Comment by danrevah** [comment]
I was able to debug using the way you showed me and I found the issue..
It was related to where I placed it on the page and for some reason it was only working for iOS. 

Now its working.. Thanks!

**Comment by erandagan** [comment]
@mahesh963 are you still experiencing this issue?
