### ISSUE TITLE
[IOS] Adchoice offset issue

### ISSUE THREAD

**Issue by Suraj-Tiwari** [callstack/react-native-fbads#151]
Current Adchoice rendering is not showing without zIndex and offset is also going out of screen

**Comment by Suraj-Tiwari** [comment]
@erandagan current implementation has some flaw in it

**Comment by erandagan** [comment]
Could you attach a screenshot? I've tested without any zIndex and everything works as it should.

**Comment by Suraj-Tiwari** [comment]
@erandagan found the issue updated docs and some fix #152
