### ISSUE TITLE
What changed between version 4 and version 5

### ISSUE THREAD

**Issue by raphaeleidus** [callstack/react-native-fbads#153]
I can't find any documentation on how the APIs or behavior changed between 4 and 5.

there is a major crash affecting the last public release of the major version 4 so I would like to use a more current version but I am not seeing what the changes were for 5 to know how to go about upgrading. Am I missing something?

**Comment by Trancever** [comment]
@raphaeleidus We don't have migration guide unfortunately. Basically whole library was rewritten and there were a lot of breaking changes, so the best option is to follow readme and integrate lib once again.
