### ISSUE TITLE
Android app stuck while ad not loading.

### ISSUE THREAD

**Issue by danrevah** [callstack/react-native-fbads#155]
I've got an ad on my main page and occasionally the ad is not loading probably due to the fact facebook is not always serving ads.. in this case the app is getting stuck and I cant xclick anything.

any ideas?

**Comment by Suraj-Tiwari** [comment]
According to my information If there is no ad from Facebook, your app will
continue to work without any issue.

**Comment by danrevah** [comment]
This is only happens to me while using Android.

**Comment by Suraj-Tiwari** [comment]
Can you share logcat?

**Comment by erandagan** [comment]
@danrevah Please share your usage - are you using Native Ads, Banners or something else?

**Comment by danrevah** [comment]
Banner ads

**Comment by erandagan** [comment]
Please update your issue according to the new issue template. Thanks!
