### ISSUE TITLE
Add Native Compilation to CI

### ISSUE THREAD

**Issue by erandagan** [callstack/react-native-fbads#166]
To ensure PRs don't break the native project compilation, we need to add the following steps to our CircleCI configuration:
- [ ] Adapt the Example project to v6 (#147)
- [ ] Compile the native example project on iOS
- [ ] Compile the native example project on Android

Any contribution on that matter (and the related #147) will be very appreciated.

**Comment by TMaszko** [comment]
We haven't received any info recently about this proposal so I'll close it for now.
