### ISSUE TITLE
Support AdOptionsView

### ISSUE THREAD

**Issue by erandagan** [callstack/react-native-fbads#171]
Starting at Audience Network 5.1.0, Facebook deprecated `AdChoicesView` and added a more robust and customisable `AdOptionsView`, which is very similar both in usage and in the looks.

We need to create a new view adapter for the added `AdOptionsView`. It will probably be a very similar implementation to `AdChoicesView`'s native adapter, so most of the existing code can be reused.

**Comment by iwantooxxoox** [comment]
@Trancever any update on supporting AdOptionsView? thanks

**Comment by Trancever** [comment]
@iwantooxxoox I am not really able to work on it right not. It would be awesome if someone from community could submit a PR implementing this.

**Comment by TMaszko** [comment]
We haven't received any info recently about this proposal so I'll close it for now.

**Comment by nihp** [comment]
Any updates on this. I really need this.

Kindly update this
