### ISSUE TITLE
Impressions not logged within ScrollView / FlatList

### ISSUE THREAD

**Issue by erandagan** [callstack/react-native-fbads#172]
**This is not a bug in this library, but more of a compatibility warning between React Native and the current native FB Audience Network SDKs.**

#### Short Background
When running Native Ads, Facebook's SDK tries to figure out exactly when a user sees an ad. For example, if an ad is shown inside a scrolling view, Facebook would ideally log an impression only if the ad was actually visible to the user.

#### The Problem
Currently, the Audience Network SDK isn't logging impressions correctly for native ads nested within React Native scroll components.

Ads are being pulled and displayed just fine - but the piece of code in FB's SDK responsible for detecting impressions isn't working with React Native's `FlatList` and `ScrollView`, which work differently from their native counterparts.

#### What Now?
I've contacted the Audience Network team to try and find a solution to this problem. I'm opening this issue to raise awareness and make sure that people understand why this might be happening in their own app.

**Comment by Suraj-Tiwari** [comment]
Previously I contacted FB Audience team regarding blurry media view,
They Were lazy, Their response feels like they don't give a damnn about
React Native Compability.
And their sdk have so many issue with React Native.

**Comment by erandagan** [comment]
That's really disappointing given how heavily Facebook invests in React Native. It appears that some decision makers in FB's monetisation platform simply don't prioritise RN..

**Comment by Suraj-Tiwari** [comment]
That's the reason I'm loosing my interest in RN...
If they make something make it useful not only for fulfilling requirements.
Since Released I filed and issue related to Performance When having multi
Touchable in list view. Still not resolved.

**Comment by Trancever** [comment]
@grabbou @satya164 Do you know someone from Facebook who we could ask about that issue?

**Comment by erandagan** [comment]
The response I received from the Audience Network team says they don't support React Native (which we already know) without any further intention to help solve this problem.

This is a major flaw, and we can't really do anything unless someone at Facebook steps in :(

**Comment by Suraj-Tiwari** [comment]
@erandagan yeah when i contacted their team regarding mediaView blur images issue, they were ignoring it completely. All the time they were like they aren't interested to support React Native ads at all

Because i think both React Native and Audience network are facebook's product they still don't have any ads library for React Native. 
Apart from that google already created Google Ads Module for flutter.

**Comment by bozzmob** [comment]
I'm facing this issue as well. Is there any solution for this?

**Comment by raphaeleidus** [comment]
I think I have an idea on the implementation problem that might be causing this

In reviewing the docs for the audience SDK I noticed this:

> add a container for your Native Ad. The container should be a `com.facebook.ads.NativeAdLayout` which is a wrapper on top of a FrameLayout with some extra functionality that enabled us to render a native Ad Reporting Flow on top of the ad.

In reviewing the source for this library there is no reference to `NativeAdLayout`. I think if we can start using it it may resolve a number of problems (on android at least)

**Comment by perrosnk** [comment]
Has anyone found a solution?

**Comment by Trancever** [comment]
@raphaeleidus Did you try using `NativeAdLayout` ? What was the result?

**Comment by Suraj-Tiwari** [comment]
According to someone's comment he tried, with no luck..

**Comment by TidamCo** [comment]
Hi, i am new to this module, managed to make it work after quite some trouble because i cannot use cocoapods, I confirm that no impressions nor clics get logged by facebook, both on ios and android, when the native ads are in a scrollview.

Has anyone thought about any workaround that would make it work ? As far as I know, this module is the only one with native ads capability ..

**Comment by perrosnk** [comment]
This library doesn't seem to be maintained. To anyone who is interested I recently discovered this: https://github.com/ammarahm-ed/react-native-admob-native-ads/

**Comment by ScottDikowitz** [comment]
This is a very frustrating, massive limitation of this package. I think it deserves a mention in the README.
It's unfortunate, because native facebook ads look much nicer than admob.

**Comment by perrosnk** [comment]
To anyone looking for a partial solution, this [library](https://github.com/ammarahm-ed/react-native-admob-native-ads) seems to work at least for Android.
On iOS, Facebook seems to log approaximately 1/3 of the impression. Check this [comment](https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/33#issuecomment-640923622)

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then I'll reopen it.
