### ISSUE TITLE
Delete old deprecated branch to prevent confusion 

### ISSUE THREAD

**Issue by Suraj-Tiwari** [callstack/react-native-fbads#178]
Branch
- AdchoiceFix
- Beta

Don't have any useful purpose. Delete those branch and create new Beta Branch and work there. No master update directly this will make release much manageable.

**Comment by Suraj-Tiwari** [comment]
@erandagan

**Comment by Suraj-Tiwari** [comment]
#174

**Comment by erandagan** [comment]
Done.
