### ISSUE TITLE
undefined function createContext

### ISSUE THREAD

**Issue by pitchourou** [callstack/react-native-fbads#180]
getting these errors after fresh install, only importing the module 
react-native-fbads@6.0.2
react-native@.51

on the simulator
<img width="522" alt="capture d ecran 2018-12-22 a 15 08 31" src="https://user-images.githubusercontent.com/16292971/50386185-5631f180-06e2-11e9-94c5-821d0af100fd.png">

on the console
<img width="832" alt="capture d ecran 2018-12-23 a 18 33 32" src="https://user-images.githubusercontent.com/16292971/50386188-5f22c300-06e2-11e9-951e-e1e7dc5eaf60.png">

**Comment by erandagan** [comment]
We don't support react native versions older than 0.55.

**Comment by pitchourou** [comment]
should be specified on the doc then
