### ISSUE TITLE
Error while linking with react native link

### ISSUE THREAD

**Issue by HasnainAD** [callstack/react-native-fbads#181]
# Bug Report

**Before opening**

-  Did you try the latest release?
Yes.
-  Did you look for existing issues?
Yes
 
**Platforms**
Xcode : Version 9.3.1  
 
**Versions**
 
- iOS: All versions
- react-native-fbads: ^6.0.2
- react-native: ^0.57.7

**Ads Environment**
 
**Current Behaviour**
After Installing with 

> npm install react-native-fbads

Running
> react-native link react-native-fbads
is causing this error 

> rnpm-install info Linking react-native-fbads ios dependencyrnpm-install ERR! Something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function
> Please file an issue here: https://github.com/facebook/react-native/issues
> buildSettings.LIBRARY_SEARCH_PATHS.push is not a function
> TypeError: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function
>     at pbxProject.addToLibrarySearchPaths (/Users/mobologics/Downloads/HASNAIN/projects/react/AwesomeProject/node_modules/xcode/lib/pbxProject.js:1237:51)
>     at pbxProject.addStaticLibrary (/Users/mobologics/Downloads/HASNAIN/projects/react/AwesomeProject/node_modules/xcode/lib/pbxProject.js:467:10)
>     at getTargets.forEach.product (/Users/mobologics/Downloads/HASNAIN/projects/react/AwesomeProject/node_modules/react-native/local-cli/link/ios/register
> NativeModule.js:61:19)
>     at Array.forEach (<anonymous>)
>     at registerNativeModuleIOS (/Users/mobologics/Downloads/HASNAIN/projects/react/AwesomeProject/node_modules/react-native/local-cli/link/ios/registerNat
> iveModule.js:56:33)
>     at Object.registerNativeModule [as register] (/Users/mobologics/Downloads/HASNAIN/projects/react/AwesomeProject/node_modules/react-native/local-cli/li
> nk/ios/common/registerNativeModule.js:15:5)
>     at Object.keys.forEach.platform (/Users/mobologics/Downloads/HASNAIN/projects/react/AwesomeProject/node_modules/react-native/local-cli/link/link.js:74
> :16)
>     at Array.forEach (<anonymous>)
>     at linkDependency (/Users/mobologics/Downloads/HASNAIN/projects/react/AwesomeProject/node_modules/react-native/local-cli/link/link.js:44:32)
>  

**Expected Behaviour**
The project should run as FacebookSDK and audience network have be added as per official docs.
 
**Steps to Reproduce**
Try to link project after installing with npm

 In my "Library Search Paths" of my Build Settings, I have : 
"$(SRCROOT)/../node_modules/react-native-webrtc/ios" without quotes.

**Comment by HasnainAD** [comment]
Please tell me the steps to manually link the files.

**Comment by erandagan** [comment]
See https://github.com/react-native-community/react-native-maps/issues/1000
