### ISSUE TITLE
Native ads MediaView image blurred and can't click ad

### ISSUE THREAD

**Issue by nullmu0** [callstack/react-native-fbads#182]
I successfully created a native ad.
But the MediaView image is blurry and can't jump when clicking on the ad.

"Version": "6.0.2"  for Android

![image](https://user-images.githubusercontent.com/955472/50394615-b2a41800-0799-11e9-98e0-7cacf57696ae.png)

    @observer
    class AdComponent extends React.Component<any> {
        render() {

        console.warn(this.props.nativeAdView)

        return (
            <Card transparent style={[styles.card, { width: width }]} >
                <CardItem style={{ borderWidth: 0 }}>
                    <Left>
                        <AdIconView style={{ width: 30, height: 30, borderRadius: 15 }} />
                        <Body>
                            <View style={{ flexDirection: 'row' }}>
                                <TouchableOpacity >
                                    <Text style={{ color: '#272727', fontSize: 13 }}>
                                        {this.props.nativeAd.headline}  {this.props.nativeAd.coverImage}
                                    </Text>
                                </TouchableOpacity>
                            </View>
                            <View style={{ flexDirection: 'row' }}>
                                <Text style={{ color: '#7F7F7F', fontSize: 12 }} >
                                    {this.props.nativeAd.sponsoredTranslation}
                                </Text>
                            </View>
                        </Body>
                    </Left>
                </CardItem>

                <CardItem cardBody>
                    <AdChoicesView style={styles.adchoice}/>
                    <MediaView style={{ flex:1, width: width, height: width * 0.55,marginHorizontal:0,alignSelf:'center',backgroundColor:'transparent' }} />
                </CardItem>

                <CardItem>
                    <TriggerableView >
                        <Text>{this.props.nativeAd.callToActionText}</Text>
                    </TriggerableView>
                </CardItem>
            </Card>

        );
        }
    }

    import { NativeAdsManager } from 'react-native-fbads';
    const adsManager = new NativeAdsManager('*****80_212310*****81', 10);
    <AdComponent adsManager={adsManager} adChoicePosition="bottomRight"  />

**Comment by Suraj-Tiwari** [comment]
Click on Image and logo is working?
Media Blur is known issue.

**Comment by junjun16818** [comment]
Not working！

Click the TriggerableView about 4 times or so, the ad unit will disappear.

**Comment by junjun16818** [comment]
Click AdChoicesView  wording

**Comment by pitchourou** [comment]
same issue here, blurred image and unclickable button 
fbads version 6.0.2
RN version: 0.57

**Comment by zensuke** [comment]
same issue.

fbads version 6.0.2
RN version: 0.55.3

**Comment by SkyTreasure** [comment]
Facing same issue on "react-native-fbads": "^6.1.0"

**Comment by gamingumar** [comment]
I am also facing the issue on android

**Comment by seomaz** [comment]
same here, only for android ads type: image

**Comment by ljubomir-digihey** [comment]
jebo vam pas mater krvavu

**Comment by shekharskamble** [comment]
any update on this? facing same issue

**Comment by a26364177** [comment]
same here
fb-ads v6.3.1
audience network v5.9.1

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then I'll reopen it.
