### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_FBAdIconView"

### ISSUE THREAD

**Issue by HasnainAD** [callstack/react-native-fbads#183]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

**Platforms**

**Versions**

- Android:
- iOS: 9
- react-native-fbads: 6.0.2
- react-native: 0.57

**Ads Environment**

Build fails regard less of device

**Current Behaviour**

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FBAdIconView", referenced from:
      objc-class-ref in libReactNativeAdsFacebook.a(EXNativeAdManager.o)
      objc-class-ref in libReactNativeAdsFacebook.a(EXAdIconViewManager.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Expected Behaviour**
Should build without any errors, as audiencenetwork is integrated fine

**Steps to Reproduce**
Try to build with above specifications.

**Additionals**

**Comment by Suraj-Tiwari** [comment]
Use audience version 50
