### ISSUE TITLE
Cannot read property 'showAd' of undefined

### ISSUE THREAD

**Issue by Vabery** [callstack/react-native-fbads#188]
# Bug Report

**Before opening**

- [ ] Did you try the latest release?
yes
- [ ] Did you look for existing issues?
yes

**Ad Modules**

Interstitial Ads

**Platforms**

Android

**Versions**

- react-native-fbads: "^6.0.2"
- react-native: "0.56.0"

**Ads Environment**

- Facebook app installed:
- Happens in test (dev build + device is marked as a test device):
- Happens in production (release build + **not** a test device):
- Facebook review status: [not submitted | approved]

**Current Behaviour**

On Android device  I get an error "Cannot read property 'showAd' of undefined" but
on ios everything works
**Expected Behaviour**

**Steps to Reproduce**

**Additionals**
![screenshot_2019-01-16-15-15-50-199_com ssbs qrscanner cashback](https://user-images.githubusercontent.com/20162994/51251454-0de4b700-19a2-11e9-863c-18f9aeb14e12.png)

**Comment by erandagan** [comment]
This means the native android module wasn't properly linked. Ensure it's linked, then recompile and run your code.

**Comment by Vabery** [comment]
@erandagan i used `[react-native link react-native-fbads]` but the error remains.

**Comment by Trancever** [comment]
@Vabery Try to link the library manually. Link sometimes doesn't work properly.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then I'll reopen it.
