### ISSUE TITLE
error while updating property 'placementId' managed by AdChoicesView

### ISSUE THREAD

**Issue by pitchourou** [callstack/react-native-fbads#189]
# Bug Report

**Before opening**

- [ ] Did you try the latest release? YES
- [ ] Did you look for existing issues? YES

**Ad Modules**
Native Ads

**Platforms**
Android

**Versions**

- Android:  8
- react-native-fbads: 6.0.2
- react-native: 0.57

**Ads Environment**

- Facebook app installed:
- Happens in test (dev build + device is marked as a test device):
- Facebook review status: [approved]

**Additionals**

![gregre](https://user-images.githubusercontent.com/16292971/51329586-20302500-1a76-11e9-8c16-9923c4795d50.jpg)

**Comment by pitchourou** [comment]
sometimes the test ads loads fine, but sometimes they don't leaving producing an error and a blank space in the app feed.

I'm trying to catch the error but not working 
`        adsManager.onAdsError(err => {
            console.log(err);
            this.setState({adsLoadFail: true});
        });` 

how to catch the ad load error properly to avoid blank spaces in the feed ?

![gregreg](https://user-images.githubusercontent.com/16292971/51330085-1955e200-1a77-11e9-9eaa-eb6898b92313.jpg)

**Comment by pitchourou** [comment]
When I remove the `<AdChoicesView />` component , the test ad displays fine

**Comment by pitchourou** [comment]
Also getting this on the console sometimes, i think it is related `1000: java.net.SocketTimeoutException: timeout`

**Comment by pratishshr** [comment]
@pitchourou Did you find a solution to this issue?

**Comment by kyungjoongo** [comment]
When I remove the <AdChoicesView /> component , the test ad displays fine

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then I'll reopen it.
