### ISSUE TITLE
error : undifined is not a function ct2.default.createContext

### ISSUE THREAD

**Issue by KhoirH** [callstack/react-native-fbads#190]
before I import the package there is no error but when I import it
error as below :

![whatsapp image 2019-01-18 at 15 19 13](https://user-images.githubusercontent.com/25068242/51374098-81b6c900-1b34-11e9-93fb-59d1ab72c970.jpeg)

react-native 0.55
react-native-natvigation 1.1.484

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
