### ISSUE TITLE
App unresponsive while waiting for an ad to be filled

### ISSUE THREAD

**Issue by dajaffe** [callstack/react-native-fbads#191]
# Bug Report

**Before opening**

- [X] Did you try the latest release? **6..0.0-rc3**
- [X] Did you look for existing issues? https://github.com/callstack/react-native-fbads/issues/155 but no traction on it.

**Ad Modules**
Banner Ads (BannerView)

**Platforms**
Android

**Versions**
- Android: SDK 27
- react-native-fbads: 6.0.0-rc3
- react-native: 0.57.5

**Ads Environment**
- Facebook app installed: **Yes**
- Happens in test (dev build + device is marked as a test device): **Yes**
- Happens in production (release build + **not** a test device): **Yes**
- Facebook review status: **Approved**

**Current Behaviour**
When a banner ad (BannerView) is waiting to be filled and displays a white bar, other network calls are blocked, and in some cases, touches aren't handled. 

**Expected Behaviour**
Loading ads should be non-blocking.

**Steps to Reproduce**
This is extremely sporadic and no real way to reproduce since it depends upon if ads are loading. I have noticed it occurs more often on the first launch of the app after installation.

**Comment by Suraj-Tiwari** [comment]
Please Share your implementation.

**Comment by dajaffe** [comment]
My overall app is fairly massive, but I get my ad rendered at the top-most level (App wrapped in react-redux Provider), and the issue occurs on startup.

Entry point - nothing else except a render()
```
      <Provider store={this.store}>
        <App />
      </Provider>
```

And <App> - Again, nothing else besides a render()
```
  render() {
    return (
      <View style={{ flex: 1 }}>
        {
          this.props.authData ?
            <MainTabNavigator /> :
            <WelcomeScreen style={{ flex: 1 }} />
        }
        {
          this.props.showAd &&
          <BannerView
            placementId="XXXX"
            type="standard"
            onPress={() => console.log('click')}
            onError={err => console.log('error', err)}
          />
        }
      </View>
    );
  }
```
My WelcomeScreen is rendered first (redux store's authData is empty on startup), which dispatches an action to try and login using stored tokens in storage and hitting an API over a network call. I can confirm that network call never occurs when the banner remains white.

Is there a way to force an ad to be stuck in a loading state so I can try debugging this?

**Comment by dajaffe** [comment]
Yeah I'm planning on digging into the native side to see if anything sticks out. I'm not super familiar with Android's native ads SDK - any recommendations on where to start? I'm thinking getting into the AdView's loadAd() method called by BannerView, then seeing if there's something in there I can force to act as if it's stuck on a call to Facebook.

**Comment by dajaffe** [comment]
I've been able to recreate this using an emulator, which 100% prevents ads from loading. I'm not really familiar with how touch events are handled (and somehow blocked), but I'll see what I can do to troubleshoot it.

**Comment by dajaffe** [comment]
I _think_ I figured it out, but I can't prove it.

My theory is the BannerView's height is spanning the entire screen upon creation (even though visibly it looks fine), then gets appropriately resized once a load finishes or errors. I'm guessing in my case, it times out after a while, at which point it then knows it's only a couple hundred pixels high.

As soon as I removed the onPress and onError, touch events were passing to my own components even though the Ad wasn't loading. 

Are there a callbacks on the BannerView for when an ad loads / ads fail to load?

**Comment by kkusanagi** [comment]
Using react-native-fbads: 6.0.2
The app crash when showing the screen that contain ads.


```

02-10 17:01:10.306 6047-6047/com.tootitoo.tootitoo E/FBAudienceNetwork: You are using custom Application class and don't call AudienceNetworkAds.isInAdsProcess(). Multi-process support will be disabled. Please call AudienceNetworkAds.isInAdsProcess() if you want to support multi-process mode.
02-10 17:01:10.320 6047-6047/com.tootitoo.tootitoo D/AdInternalSettings: Test mode device hash: e37b0138-06c1-45c1-a1d2-3bdc07e1cb0b
    When testing your app with Facebook's ad units you must specify the device hashed ID to ensure the delivery of test ads, add the following code before loading an ad: AdSettings.addTestDevice("e37b0138-06c1-45c1-a1d2-3bdc07e1cb0b");
02-10 17:01:10.327 6047-6047/com.tootitoo.tootitoo D/IS_UNITY: false
    
    --------- beginning of system
02-10 17:01:10.401 6047-6233/com.tootitoo.tootitoo E/ActivityThread: Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
02-10 17:01:10.409 1551-5250/? I/GnssLocationProvider: WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@a80b6d1)
02-10 17:01:10.453 6047-6119/com.tootitoo.tootitoo D/EGL_emulation: eglMakeCurrent: 0xb3207100: ver 2 0 (tinfo 0x9507fa00)
02-10 17:01:10.459 6047-6052/com.tootitoo.tootitoo I/art: Do partial code cache collection, code=122KB, data=101KB
02-10 17:01:10.464 6047-6052/com.tootitoo.tootitoo I/art: After code cache collection, code=113KB, data=96KB
    Increasing code cache capacity to 512KB
02-10 17:01:10.465 1551-1563/? I/GnssLocationProvider: WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@a80b6d1)
02-10 17:01:10.478 1551-1959/? I/GnssLocationProvider: WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@e53e5a4)
02-10 17:01:10.479 6047-6119/com.tootitoo.tootitoo D/EGL_emulation: eglMakeCurrent: 0xb3207100: ver 2 0 (tinfo 0x9507fa00)
02-10 17:01:10.479 1551-1563/? I/GnssLocationProvider: WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@e53e5a4)
02-10 17:01:10.515 6047-6233/com.tootitoo.tootitoo V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {4043b8a}
02-10 17:01:10.525 5837-5881/? W/GCoreFlp: No location to return for getLastLocation()
02-10 17:01:10.574 6047-6047/com.tootitoo.tootitoo I/cr_LibraryLoader: Expected native library version number "51.0.2704.90", actual native library version number "51.0.2704.90"
02-10 17:01:10.610 6047-6047/com.tootitoo.tootitoo I/chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
02-10 17:01:10.763 6047-6047/com.tootitoo.tootitoo I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
02-10 17:01:10.902 6047-6047/com.tootitoo.tootitoo E/ApkAssets: Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
    Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
02-10 17:01:11.851 6047-6047/com.tootitoo.tootitoo D/EGL_emulation: eglCreateContext: 0x83a1d600: maj 2 min 0 rcv 2
02-10 17:01:11.856 6047-6047/com.tootitoo.tootitoo D/EGL_emulation: eglMakeCurrent: 0x83a1d600: ver 2 0 (tinfo 0xa5a66f70)
```

**Comment by tmjordan** [comment]
I have a similar problem with network, i also think that the ad is blocking other network calls.

**Comment by maphongba008** [comment]
Any updates on this issue? I was stuck with this for many days :(
I've checked log in xcode, after request ad fail (due to "No network" error), it keeps requesting ad, many error log show there, don't know if it's native code issue or not

**Comment by maphongba008** [comment]
Work around for me:
Comment all of the error handler in EXBannerView.m wont make app freeze:
- (void)adView:(FBAdView *)adView didFailWithError:(NSError *)error
```
{
//  if (_onAdError) {
//    _onAdError(RCTJSErrorFromNSError(error));
//  } else {
//    RCTMakeAndLogError(error.localizedDescription, nil, error.userInfo);
//  }
}
```

**Comment by Jeadonara** [comment]
I had some issue too, removing onPress and onError parameters worked fine.

**Comment by waiyan112** [comment]
> I had some issue too, removing onPress and onError parameters worked fine.

Thank you, Problem solved.

**Comment by AKKIDETROJA** [comment]
** #I had some issue too, removing onPress and onError parameters worked fine.**

its working fine

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
