### ISSUE TITLE
[IOS] BannerView shows as thin line

### ISSUE THREAD

**Issue by yyohanes** [callstack/react-native-fbads#192]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

Banner Ads

**Platforms**

IOS

**Versions**

- iOS: 12.1
- react-native-fbads: 6.0.2
- react-native: 0.56

**Ads Environment**
- Facebook app installed: No. This is simulator.
- Happens in test (dev build + device is marked as a test device): Yes
- Happens in production (release build + **not** a test device): Not tested
- Facebook review status: approved

**Current Behaviour**

Banner ads appear thin, like 1px width.
Not sure if this is related, there was this issue that was closed: https://github.com/callstack/react-native-fbads/issues/76

**Expected Behaviour**

Banner ads has correct width. In my case, `rectangle` should have width of 300

**Steps to Reproduce**

Use `<BannerView/>` component

**Additionals**

![screenshot 2019-01-31 at 10 29 22 pm](https://user-images.githubusercontent.com/661080/52065203-9b322900-25a8-11e9-9cc9-093602cee148.png)

**Comment by tmjordan** [comment]
I have exactly the same problem :-/

**Comment by bemnet4u** [comment]
+1 I spent few days debugging this thinking its my code :(

**Comment by Dinesh-In** [comment]
I have little experience with C coding. 
But based on #76 i tried this and it worked. 
I am using  
 "react": "16.6.3",
 "react-native": "0.58.6",
"react-native-fbads": "^6.1.0",
 "react-native-fbsdk": "0.9.0",

modify /node_modules/react-native-fbads/ios/ReactNativeAdsFacebook/EXBannerView.m
 
change :-

  adView.frame = CGRectMake(0, 0, adView.bounds.size.width, adView.bounds.size.height);
  adView.delegate = self;

to 
  adView.frame = CGRectMake(0, 0, adView.bounds.size.width, adView.bounds.size.height);
// add this line
  adView.autoresizingMask = UIViewAutoresizingFlexibleWidth;
  adView.delegate = self;

**Comment by tmjordan** [comment]
@Dinesh-In thank you man, your saved my day.

**Comment by RodolfoGS** [comment]
Thank you @Dinesh-In, I created a PR with your fix and works great https://github.com/callstack/react-native-fbads/pull/231

**Comment by RodolfoGS** [comment]
Anyone to review my PR that fix this issue? https://github.com/callstack/react-native-fbads/pull/231

**Comment by Suraj-Tiwari** [comment]
#231 fix merged
