### ISSUE TITLE
Rewarded Video Support?

### ISSUE THREAD

**Issue by travisgreermoguls** [callstack/react-native-fbads#194]
It looks like Rewarded Video was supported (via pull request) at one point in time, probably in v3.X - #98, #95. 

While it seems the PR was merged to master, I can't seem to find rewarded video support currently.  Was support actively dropped from v4.X?  Or maybe I'm missing something else.

It would be great to get support for rewarded video in the package.  I would be happy to do what I can to help.

**Comment by Trancever** [comment]
@travisgreermoguls Yes, you'r right. In the past, we were supporting Rewarded Video Ads but, since the package was full of bugs we decided to rewrite it from scratch and we dropped support for this type of ads.

Right now, we have limited time to work on this package, so we are really happy about external contributions. Would be cool if you could bring support for Rewarded ads back :)

**Comment by travisgreermoguls** [comment]
@Trancever, thanks for the update.  It's not my forte, but I'll take a stab at it.

**Comment by travisgreermoguls** [comment]
@Trancever , I've made an attempt at this.  I've combined the previous v3.X implementation with the v4.X changes observed in EXInterstitialAdManager.  

Everything appears to work well - except that an iOS rewarded video window will not respond to the dismiss button ('X').  

I'm out of my depth and have been unable to figure this out.  If you or someone on your team has extra time to take a look, I would really appreciate it.  Maybe I've done something obviously wrong?  I'm happy to apply any direction or advice.

I've forked and added the feature in my repo: https://github.com/travisgreermoguls/react-native-fbads.  It'd be great to get my changes to the point to do a pull request and add rewarded video.

**Comment by Suraj-Tiwari** [comment]
@erandagan can you have a look?

**Comment by travisgreermoguls** [comment]
Just to circle back on this, we went with AdMob with Facebook Audience Network ad mediation to meet our rewarded video need.  You're welcome to pull anything useful from my work, but I don't foresee finishing it up at this point.  Thanks!

**Comment by tomhicks** [comment]
@travisgreermoguls could you possibly explain how you set up Facebook Audience Network ad mediation on Admob with React Native?

Thanks in advance.

**Comment by travisgreermoguls** [comment]
I believe we ended up using react-native-firebase, which has an admob component.  Then you have to go through and configure things on admob to use facebook audience network.  On top of that, you have to have the facebook video support in your binary.  It was relatively involved and a while back, so I don't recall all the details.
