### ISSUE TITLE
An error occurred after upgrading to react native 0.58.5

### ISSUE THREAD

**Issue by nullmu0** [callstack/react-native-fbads#196]
![5871550709621_ pic](https://user-images.githubusercontent.com/955472/53135027-8bf53880-35b4-11e9-88a6-b4d450e294d5.jpg)

**Comment by junjun16818** [comment]
In NativeAdManager.java add some code
Can solve this error
```
+ import com.facebook.react.module.annotations.ReactModule;
+ @ReactModule(name = "CTKNativeAdManager")
public class NativeAdManager extends ReactContextBaseJavaModule implements NativeAdsManager.Listener {
```

**Comment by perrosnk** [comment]
Any updates?

**Comment by Suraj-Tiwari** [comment]
If your fix resolved the problem Please submit a PR, I'll approve it.

**Comment by thymikee** [comment]
We've released v7 today with support for latest RN versions. Please upgrade :)
