### ISSUE TITLE
InterstitialAdManager ads not show error { "framesToPop": 1, "code": "E_FAILED_TO_LOAD" } 

### ISSUE THREAD

**Issue by AkshayItaliya** [callstack/react-native-fbads#197]
**Platforms**

**Versions**

- Android:
- iOS:
- react-native-fbads:
- react-native:

**Ads Environment**

- Facebook app installed:
- Happens in test (dev build + device is marked as a test device):
- Happens in production (release build + **not** a test device):
- Facebook review status: [not submitted | approved]

**Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
