### ISSUE TITLE
Error TypeScript

### ISSUE THREAD

**Issue by vietnux** [callstack/react-native-fbads#200]
It has an error on file  \node_modules\react-native-fbads\dist\types\native-ads\withNativeAd.d.ts

> Information:Cannot find parent 'tsconfig.json'
> Error:(47, 19) TS2503: Cannot find namespace 'JSX'.

I install  npm install -g typescript and ES6 but it does not fail
Help me!

**Comment by Suraj-Tiwari** [comment]
fixed in a recent release.
