### ISSUE TITLE
[Feature] NativeAdScrollView (Horizontal Scroll For Native Ads)

### ISSUE THREAD

**Issue by mehuleo** [callstack/react-native-fbads#202]
Hi,
Request to impletement NativeAdScrollView.
Ref: https://developers.facebook.com/blog/post/2015/05/06/native-ads-made-easy/ https://developers.facebook.com/docs/audience-network/reference/android/com/facebook/ads/nativeadscrollview.html/?version=v4.99.1

This would help boost the revenues for many.
Thanks.

**Comment by TMaszko** [comment]
We haven't received any info about this proposal recently so I'll close it for now
