### ISSUE TITLE
Error while updating property 'adsManager' of a view managed by: CTKNativeAd

### ISSUE THREAD

**Issue by techday84** [callstack/react-native-fbads#203]
# Bug Report

**Before opening**

- [ ] Did you try the latest release? YES
- [ ] Did you look for existing issues? YES

**Ad Modules**
Native Ads

**Platforms**
Android

**Versions**
- Android: 7.0

- react-native-fbads: "6.1.0",

- react-native:
react-native-cli: 2.0.1
react-native: 0.59.5

**Ads Environment**

- Facebook app installed: YES
- Happens in test (dev build + device is marked as a test device):
- Happens in production (release build + **not** a test device):
- Facebook review status: [not submitted | approved] approved

**Additionals**

Error while updating property 'adsManager' of a view managed by: CTKNativeAd
null
Could not find @ReactModule annotation in suraj.tiwari.reactnativefbads.NativeAdManager

I can see the request in https://business.facebook.com but the app doesn't show ads, only the error:

"Error while updating property 'adsManager' of a view managed by: CTKNativeAd
null
Could not find @ReactModule annotation in suraj.tiwari.reactnativefbads.NativeAdManager"

**Comment by joakimwennergren** [comment]
I'm getting the same error all of a sudden on my android devices. It's working on IOS though.

**Comment by techday84** [comment]
With react-native: 0.55.4 it "works".
This error disappears but the ads are blurry images and when it happens, the link doesn't work.
When the ad shows a carrousel of images, the images are ok and the link works.

**Comment by Suraj-Tiwari** [comment]
Blurry media view is a known issue, issue is within audience sdk, not
library

**Comment by hazeeb** [comment]
I'm having same issue in react-native: 0.58.4

**Comment by mehuleo** [comment]
Following fix helped me get around this issue:

Open: `node_modules/react-native-fbads/android/app/src/main/java/suraj/tiwari/reactnativefbads/NativeAdManager.java` and add the following line:

```java
@ReactModule(name = "CTKNativeAdManager") // <-- Add this line
public class NativeAdManager extends ReactContextBaseJavaModule implements NativeAdsManager.Listener {

`

**Comment by hazeeb** [comment]
@mehuleo Thank you for your support. It worked, but ads are burred.

**Comment by Trancever** [comment]
@mehuleo Could you submit PR with that fix?

**Comment by mehuleo** [comment]
@hazeeb Please read this thread: https://github.com/callstack/react-native-fbads/issues/132
In my experience, the blurry ad won't be a big issue, if you reload the app it'll go away, although if your end-users' internet speed is slow then the Native Ad will render blurry frequently.
I've used Native Ads on production and CTR is 1.5-2 times higher compared to Banner Ad so, impression drop due to the blurry image will be compensated by high CTR. So, your Native Ad unit will still generate more revenue than that of a Banner Ad unit.

**Comment by mehuleo** [comment]
@Trancever Sure will do.

**Comment by Trancever** [comment]
@mehuleo Awesome, thanks!
