### ISSUE TITLE
Android test ads working but not in production

### ISSUE THREAD

**Issue by harryt2** [callstack/react-native-fbads#206]
Everything works perfectly when I'm using test ads, but when I remove the addTestDevice() method and use --variant=release the ads don't load. I have no idea what it could be. It throws an error that looks like:

'error', { dispatchConfig: { registrationName: 'onAdError' },
06-13 21:27:28.712   902  1048 I ReactNativeJS:   _targetInst: 
06-13 21:27:28.712   902  1048 I ReactNativeJS:    { tag: 5,
06-13 21:27:28.712   902  1048 I ReactNativeJS:      key: null,
06-13 21:27:28.712   902  1048 I ReactNativeJS:      elementType: 'CTKBannerView',
06-13 21:27:28.712   902  1048 I ReactNativeJS:      type: 'CTKBannerView',
06-13 21:27:28.712   902  1048 I ReactNativeJS:      stateNode: 
06-13 21:27:28.712   902  1048 I ReactNativeJS:       { _nativeTag: 2349,
06-13 21:27:28.712   902  1048 I ReactNativeJS:         _children: [],
06-13 21:27:28.712   902  1048 I ReactNativeJS:         viewConfig: 
06-13 21:27:28.712   902  1048 I ReactNativeJS:          { directEventTypes: 
06-13 21:27:28.712   902  1048 I ReactNativeJS:             { onAdError: { registrationName: 'onAdError' },
06-13 21:27:28.712   902  1048 I ReactNativeJS:               onAdPress: { registrationName: 'onAdPress' },
06-13 21:27:28.712   902  1048 I ReactNativeJS:               onLoggingImpression: { registrationName: 'onLoggingImpression' } },
06-13 21:27:28.712   902  1048 I ReactNativeJS:            NativeProps: 
06-13 21:27:28.712   902  1048 I ReactNativeJS:             { marginTop: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               opacity: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               width: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginEnd: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               right: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               minWidth: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               start: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flexBasis: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               display: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flexDirection: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityStates: 'Array',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingTop: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flex: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderWidth: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               maxHeight: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               transform: 'Array',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingHorizontal: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               rotation: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityComponentType: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               alignSelf: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               translateY: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginBottom: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               overflow: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               end: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               alignContent: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               padding: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginVertical: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingRight: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               top: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               aspectRatio: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderBottomWidth: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               onLayout: 'boolean',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flexShrink: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityRole: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               scaleX: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginRight: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityHint: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               justifyContent: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flexWrap: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderTopWidth: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderLeftWidth: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               scaleY: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               testID: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               importantForAccessibility: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               margin: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginLeft: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingBottom: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginHorizontal: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderRightWidth: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingStart: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityLabel: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               zIndex: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               height: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderStartWidth: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               bottom: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               translateX: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityLiveRegion: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               alignItems: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderEndWidth: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               elevation: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingEnd: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               minHeight: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingVertical: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               nativeID: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               placementId: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginStart: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               left: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               backgroundColor: 'Color',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               size: 'number',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               position: 'String',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingLeft: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               renderToHardwareTextureAndroid: 'boolean',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               maxWidth: 'mixed',
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flexGrow: 'number' },

06-13 21:27:28.712   902  1048 I ReactNativeJS:            uiViewClassName: 'CTKBannerView',

06-13 21:27:28.712   902  1048 I ReactNativeJS:            validAttributes: 
06-13 21:27:28.712   902  1048 I ReactNativeJS:             { marginTop: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               opacity: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               width: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginEnd: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               right: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               minWidth: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               start: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flexBasis: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               display: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flexDirection: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityStates: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingTop: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               flex: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               borderWidth: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               maxHeight: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               transform: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               paddingHorizontal: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               rotation: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               accessibilityComponentType: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               alignSelf: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               translateY: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               marginBottom: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               overflow: true,
06-13 21:27:28.712   902  1048 I ReactNativeJS:               end: true,`

**Comment by TMaszko** [comment]
lease check out v7 available now ! :) if it isn't fixed then I'll reopen it.
