### ISSUE TITLE
Ads doesn't display only in my mobile

### ISSUE THREAD

**Issue by chrismathews2007** [callstack/react-native-fbads#209]
Ads showing in other devices, but **sometimes doesn't display for longtime only in my device**. I don't know why. 

> Last time i used my mobile as test device. 

Please let me know what happening.

Thank you

**Comment by Suraj-Tiwari** [comment]
Production or test environment?

**Comment by chrismathews2007** [comment]
@Suraj-Tiwari Production 

[https://play.google.com/store/apps/details?id=com.christenpro](url)

**Comment by Suraj-Tiwari** [comment]
Try changing Facebook account.

**Comment by chrismathews2007** [comment]
I logged into CP App with an email in my device, still doesn't display, and used same credentials in another device ads are displaying...

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
