### ISSUE TITLE
how to show banner ads only after ads received....In my case white portion is there before receiving ads in bannerview??

### ISSUE THREAD

**Issue by rowheat02** [callstack/react-native-fbads#210]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [ ] Did you look for existing issues?

**Ad Modules**

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-fbads:
- react-native:

**Ads Environment**

- Facebook app installed:
- Happens in test (dev build + device is marked as a test device):
- Happens in production (release build + **not** a test device):
- Facebook review status: [not submitted | approved]

**Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

**Comment by rowheat02** [comment]
![Screenshot_20190710-212509](https://user-images.githubusercontent.com/40065760/60983961-9abd6b80-a35a-11e9-8e49-3a2def1c9fdf.jpg)

I want this view only shown after ads received

**Comment by rowheat02** [comment]
Here is the code snippet

import React, { Component } from 'react'
import {  View,ScrollView } from 'react-native'
import { BannerView, InterstitialAdManager,AdSettings } from 'react-native-fbads';
import { Container, Header, Title, Content, Footer, FooterTab, Left, Right, Body, Icon, Text,Button } from 'native-base';
import { throwStatement } from '@babel/types';

export default class App extends Component {

  constructor(props) {
    super(props)
  
    this.state = {
       hasAD:true
    };
  };


  

  showadd = () => {
    console.warn("Clicked")
    InterstitialAdManager.showAd("402919963655241_403320853615152")
      .then(didClick => { })
      .catch(error => { });

  }
  componentDidMount() {
    AdSettings.clearTestDevices();
    AdSettings.addTestDevice("5bbc3666-9023-4678-9217-2c3496b16da9");
  }

  render() {

    return (
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='menu' />
            </Button>
          </Left>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right />
        </Header>
        
        <Button bordered  onPress={this.showadd}>
            <Text>Show AD</Text>
          </Button>

          <ScrollView>

          
            
        
        <Text> Testing hai </Text>
        <Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
</ScrollView>

{<View style={{}} >
<BannerView
        placementId="402919963655241_403304910283413"
        type="standard"
        onPress={() => console.log('click')}
        onError={err => console.log('error', err)}
        //onAdViewDidReceiveAd={this.onReceived}
      />

</View>}




        
      
      
     
      </Container>

      
      

    )
  }
}

**Comment by rowheat02** [comment]
here is the code `import React, { Component } from 'react'
import {  View,ScrollView } from 'react-native'
import { BannerView, InterstitialAdManager,AdSettings } from 'react-native-fbads';
import { Container, Header, Title, Content, Footer, FooterTab, Left, Right, Body, Icon, Text,Button } from 'native-base';
import { throwStatement } from '@babel/types';

export default class App extends Component {

  constructor(props) {
    super(props)
  
    this.state = {
       hasAD:true
    };
  };


  

  showadd = () => {
    console.warn("Clicked")
    InterstitialAdManager.showAd("402919963655241_403320853615152")
      .then(didClick => { })
      .catch(error => { });

  }
  componentDidMount() {
    AdSettings.clearTestDevices();
    AdSettings.addTestDevice("5bbc3666-9023-4678-9217-2c3496b16da9");
  }

  render() {

    return (
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='menu' />
            </Button>
          </Left>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right />
        </Header>
        
        <Button bordered  onPress={this.showadd}>
            <Text>Show AD</Text>
          </Button>

          <ScrollView>

          
            
        
        <Text> Testing hai </Text>
        <Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
<Text>All the speed he took, all the turns he’d taken and the amplified breathing of the deck sting his palm as he made his way down Shiga from the sushi stall he cradled it in his devotion to esoteric forms of tailor-worship. Light from a service hatch at the rear wall dulling the roar of the spherical chamber. It was chambered for .22 long rifle, and Case would’ve preferred lead azide explosives to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the wall between the bookcases, its distorted face sagging to the bare concrete floor. Light from a service hatch at the rear of the spherical chamber. Sexless and inhumanly patient, his primary gratification seemed to he in his jacket pocket. Case felt the edge of the previous century. Still it was a long strange way home over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Case felt the edge of the console in faded pinks and yellows. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the tunnel’s ceiling.
</Text>
</ScrollView>

{<View style={{}} >
<BannerView
        placementId="402919963655241_403304910283413"
        type="standard"
        onPress={() => console.log('click')}
        onError={err => console.log('error', err)}
        //onAdViewDidReceiveAd={this.onReceived}
      />

</View>}




        
      
      
     
      </Container>

      
      

    )
  }
}


`

**Comment by Suraj-Tiwari** [comment]
You can make use of `onLoad={() => console.log('loaded')}`

**Comment by Acetyld** [comment]
` 
  const [fbLoading, setFBLoading] = useState(true);
  console.log('FacebookAd Loaded',fbLoading);
    return (
      // <View style={[styles.container]}>
      <View style={styles.bannerContainer}>
        <View style={[{justifyContent: 'center'},fbLoading ? {height: 0} : {}]}>
          <BannerView
            placementId={BANNER_TEST_UNIT_ID_ANDROID_FB}
            type="standard"
            onPress={() => console.log('click')}
            onLoad={() => {
              console.log('FACEBOOK LOADED');
              setFBLoading(false);
            }}
            onError={() => {
              console.log('FACEBOOK ERROR');
              setAd('o');
            }}/>
        </View>
        {fbLoading &&
        <View style={{
          alignSelf: 'stretch',
          height: 60,
          borderRadius: 10,
          borderWidth: 2,
          borderColor: 'black',
        }}>
          <DefaultAd type="FB"/>
        </View>
        }
      </View>`
