### ISSUE TITLE
ads not showing banner and Interstitial test ads working but in production not working & facebook approved properties

### ISSUE THREAD

**Issue by saqib006** [callstack/react-native-fbads#211]
Interstitial error:  The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK // Interstitial error
banner error // syntheticEvent {dispatchConfig: {…},....

**Before opening**

- [ yes] Did you try the latest release?
- [no ] Did you look for existing issues?

**Ad Modules**

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-fbads:6.1.0
- react-native:0.59.9

**Ads Environment**

- Facebook app installed: yes
- Happens in test (dev build + device is marked as a test device):
- Happens in production (release build + **not** a test device):
- Facebook review status: [approved]

**Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

**Comment by yogeshmoradiya121** [comment]
same issue
please help if some one fix this

**Comment by JustSevi4** [comment]
the same. Is anyone has found resolution?

**Comment by Acetyld** [comment]
Same here..

**Comment by neghani** [comment]
![image](https://user-images.githubusercontent.com/3122399/93001751-08f95180-f54f-11ea-8bf1-c74c23e398c5.png)
The highlighted could be reason for ads not displaying, I am gonna wait till go to production and post the update here.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
