### ISSUE TITLE
iOS build fails RN 0.60

### ISSUE THREAD

**Issue by jayjac** [callstack/react-native-fbads#212]
**Ad Modules**

**Versions**
- XCode 10.3
- iOS: 12.1
- react-native-fbads:
- react-native: 0.60

**Ads Environment**

- Happens whenever I tried to run from Xcode or from react-native run-ios
- Facebook review status: not submitted

**Current Behaviour**
Build fails instantly after running react-native link. Seems like some RCT headers are not found by this library and I get an immediate failure.

**Expected Behaviour**
Should build with no error.

**Steps to Reproduce**
Followed the installation instructions and hit run.
I tried without react-native link but it still doesn't work.

**Comment by abhaynpai** [comment]
@Suraj-Tiwari @erandagan 

I have created a PR #213 to fix this issue. Kindly review.

**Comment by Suraj-Tiwari** [comment]
#216 merged,
