### ISSUE TITLE
could you please publish the newest version to npm

### ISSUE THREAD

**Issue by doublelam** [callstack/react-native-fbads#215]
hey, could you please publish the latest version to npm, because the npm module is still not  a latest version, thank you

**Comment by Dinesh-In** [comment]
It would be helpful for all to use the following fixes that have already been verified/ merged  but are not available in the release 6.1.0
- hook for onAdLoad for BannerView
- Error while updating property 'adsManager' of a view managed by: CTKNativeAd

Please publish the latest version to npm.

**Comment by Suraj-Tiwari** [comment]
It'll be released

**Comment by andreiciceu** [comment]
hello; any news on this issue?
