### ISSUE TITLE
Warning: Using deprecated "rnpm" config for RN >= 0.60

### ISSUE THREAD

**Issue by abhaynpai** [callstack/react-native-fbads#217]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**
NA

**Platforms**
Android

**Versions**

- Android: API > 21
- iOS: - 
- react-native-fbads: 6.1.0
- react-native: 0.60.4

**Ads Environment**

- Facebook app installed: NA
- Happens in test (dev build + device is marked as a test device): YES
- Happens in production (release build + **not** a test device): YES
- Facebook review status: [not submitted | approved] NA

**Current Behaviour**
A warning stating 
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
- react-native-fbads: https://github.com/callstack/react-native-fbads
```

**Expected Behaviour**
Moving away from RNPM config to remove this warning.

**Steps to Reproduce**
`react-native run-android`

**Additionals**
-

**Comment by Suraj-Tiwari** [comment]
#216

**Comment by abhaynpai** [comment]
@Suraj-Tiwari : #216 is unrelated to this issue. I suggest you to re-open.

The following object should be removed from `package.json` as per [this stackoverflow post](https://stackoverflow.com/questions/57038718/the-following-packages-use-deprecated-rnpm-config-that-will-stop-working-from).

https://github.com/callstack/react-native-fbads/blob/31ec06337cfe1cc911f2aedf0fe60e735c733051/package.json#L35

I don't know the repercussions of removing it. So if you know any devs who can help out then tag them to this issue.
