### ISSUE TITLE
Banners Ads are not blurry in Skype which is developed in React Native

### ISSUE THREAD

**Issue by christenpro** [callstack/react-native-fbads#220]
@erandagan @Suraj-Tiwari Recently I checked in a banner ad in ### **Mobile Skype App**. It's not blurry, then why we are not able to resolve. And Image ads are not clickable. Please take a look at image blur.

Thank you 
![Screenshot_2019-09-13-16-17-52-267_com skype raider](https://user-images.githubusercontent.com/36419521/65300307-a0240700-db90-11e9-9d47-5d89a4125bbb.png)

**Comment by Suraj-Tiwari** [comment]
Looks like these ads are rendered from native side. 
I investigated the issue of blur ads, it's because component wasn't able to detect size of layout.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
