### ISSUE TITLE
Black screen after watching Interstitial ad on iOS 13.

### ISSUE THREAD

**Issue by JustSevi4** [callstack/react-native-fbads#221]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

**Platforms**

**Versions**

- iOS: 13
- react-native-fbads: 6.2.1
- react-native: 0.60.5

**Ads Environment**
After wathing Interstitial ad on iOS 13 I got black screen for all application. It's only on iOS 13.

**Comment by iwantooxxoox** [comment]
@JustSevi4 Did you solve the issue?

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
