### ISSUE TITLE
CTKBanner view not found in UIManager

### ISSUE THREAD

**Issue by AB91189** [callstack/react-native-fbads#224]
Hi,

I am facing the follwoing issue in react native ads.

![error](https://user-images.githubusercontent.com/12932818/66199900-69d0a680-e6bd-11e9-951b-f6999906ebb5.jpeg)

**Comment by knightkhan** [comment]
i also facing similar problem

**Comment by apjinfosolution** [comment]
Did you solve this problem??

**Comment by AB91189** [comment]
Yes

**Comment by apjinfosolution** [comment]
where is solution?

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
