### ISSUE TITLE
Module dispatched on non-UI thread on iOS

### ISSUE THREAD

**Issue by jayjac** [callstack/react-native-fbads#227]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

**Platforms**

**Versions**

- iOS: iOS simulator 12.2 and device + simulator running 13.1
- react-native-fbads: latest
- react-native: 0.61

**Ads Environment**

- Facebook app installed: yes, latest.
- Happens in test (dev build + device is marked as a test device): yes

- Facebook review status: not submitted

**Current Behaviour**
When I test out interstitial ads on iOS (with test mode on), I get the main UI thread check warning in the XCode console.
The ObjC code does not specify the dispatch_queue so methods are invoked on a background thread.
I think the iOS native code should specify
```objective-c
- (dispatch_queue_t)methodQueue
{
  return dispatch_get_main_queue();
}
```

**Expected Behaviour**
No UI thread check warning should occur.
Should consistently show interstitial ads.

**Steps to Reproduce**
Install the latest version with React-Native 0.61
(FYI: No need to use react-native link)
Run code with `InterstitialAdManager.showAd(placementId)` in javascript
I did use 
```js 
AdSettings.addTestDevice(AdSettings.currentDeviceHash)
``` 
to only get test ads.
Observe inconsistent behaviour.

**Additionals**

**Comment by Un3qual** [comment]
Did you ever find a fix for this?

**Comment by mrousavy** [comment]
Fixed with https://github.com/callstack/react-native-fbads/pull/264
