### ISSUE TITLE
Try to display fbads without login with facebook account

### ISSUE THREAD

**Issue by grean** [callstack/react-native-fbads#228]
Hi,
I've setup my ads with banners and interstitials but they are shown only if i'm connected with a facebook account.
Same behavior in Test and Release mode.
**Module ads concerned**
- Banner Ads
- Interstitial Ads
**Platforms**
- Android
**Versions**
- Android: api29 emulator and on device android 7.0
- react-native-fbads:6.3.0
- react-native:0.61.1

**Ads Environment**
- Facebook app installed: no
- Happens in test (dev build + device is marked as a test device):
- Happens in production (release build + not a test device and with a test device):
- Facebook review status: [approved + an other account not approved]

**Current Behaviour**
Need to login with facebook to see ads showing correctly. After that, i can restart my app and it continues to work well. When i logout or erase app data it won't work anymore if i login with an other accoun

**Expected Behaviour**
Thought that ads are showing even if i'm connected with a google account or enterprise account.
Without any link with a facebook connexion.

**Comment by grean** [comment]
This is due to the fact that my app was not installed from the play store or app store.
This information is findable when you go to the statistics of a block add in the FB monetize manager dashboard.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
