### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dr-andy** [callstack/react-native-fbads#233]
The library loads new ads in the background and this causes a memory leak. After some time the app becomes unresponsive. What may be the problem?

**Comment by Suraj-Tiwari** [comment]
Assuming you're talking about native ads
default limit is 10 ads, in mid range devices that can be issue, if you are using is only once and show next ad with different id, then pass the ads limit along with id.

**Comment by RodolfoGS** [comment]
I have memory leak too (on iOS, I didn't tested on Android yet), I'm trying to implement native ads in a FlatGrid, any suggestion?

**Comment by RodolfoGS** [comment]
I found an issue (and a solution), when you use native ads in a scroll view, you must to render the native ad ONLY when it is visible (on viewport). If you render the ad when it's down on the scroll your FPS will down dramatically.

### My experience using FlatList

**Without native ads (60 FPS)**
![1](https://user-images.githubusercontent.com/870365/70254760-3a84f700-174b-11ea-8909-c7038ff8bb2b.png)

**With 1 native ad in the first row, visible: (60 FPS)**
![2](https://user-images.githubusercontent.com/870365/70254821-538da800-174b-11ea-948c-1a0a3e6fe362.png)

**With 2 native ads, one in the first row and one in the 5th row, out of viewport (40 FPS):**
![3](https://user-images.githubusercontent.com/870365/70254901-761fc100-174b-11ea-8659-989867b26abe.png)

**With 3 native ads, 1st row, 5th row, 10th row, 2 out of viewport (23 FPS):**
![4](https://user-images.githubusercontent.com/870365/70254956-8b94eb00-174b-11ea-8a3e-b45751119d80.png)

----
### Solution:
Use this approach to know when the native ad is visible and render ONLY when it is.
https://stackoverflow.com/a/45869559/1687136

Additional to this I only enabled native ads of images from the Facebook Monetization Manager, if you enable video ads, the FPS slow down again.
![image](https://user-images.githubusercontent.com/870365/70255806-f4c92e00-174c-11ea-854e-425440fbb17a.png)

**Comment by garrett-gottlieb** [comment]
This is a serious problem. Video ads are unusable, experiencing same performance decrease.

**Comment by RodolfoGS** [comment]
> This is a serious problem. Video ads are unusable, experiencing same performance decrease.

It's true, I have the same problem. Video ads are unusable.

**Comment by garrett-gottlieb** [comment]
Not rendering in a list isn’t an option, either, since the height of the ad affects the position of elements below it. You’d need to render a replacement. Even so, a single photo ad reduces FPS on my iPhone XS to 50. How is anybody using this in production???

**Comment by mrousavy** [comment]
I think this is related to https://github.com/callstack/react-native-fbads/issues/238, since this might be the function repeatedly checking if the ad is visible that's causing those FPS drops

**Comment by RodolfoGS** [comment]
I don't know how Facebook doesn't have an official library for Facebook Ads, since react is from Facebook ¯\\\_(ツ)_/¯ 
This is the only library that exists and it's a junk, is not maintained and doesn't work, this issue have 1 year 🙄

@mrousavy I recommend you try to fix it (and if you fix it please open a PR 🙏) or use another network, like AdMob

**Comment by mrousavy** [comment]
Google AdMob doesn't have an official SDK for react native either, there's two libraries:

* One from react-native-firebase which doesn't support native ads
* One for native ads only from a single dev who made the library to exactly fit his needs, for my use case the library had too many bugs.

I just got invited to collab on this project and will try to fix some bugs that I come across. It would help if you could provide me as much detail as possible, e.g. by providing crash logs or clear steps to reproduce.

**Comment by abhaynpai** [comment]
I was trying to find the memory leak issue for months now. And finally after a long period of intense memory analysis I figured out that this plugin was causing the issue. I've removed it from my project just now, but guys please let's try to find the root cause of this memory leak in this project.

My analysis is that as the user navigates to any of the pages in the Android/iOS app, and then comes back to the previous page/tab, there would be a memory leak. If this can help you guys identify the root cause of this memory leak then please let me know.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
