### ISSUE TITLE
Rendering NativeAd multiple times shows same ad, not different ones

### ISSUE THREAD

**Issue by garrett-gottlieb** [callstack/react-native-fbads#235]
# Bug Report

**Before opening**

- [X] Did you try the latest release?
- [X] Did you look for existing issues?

**Ad Modules**

Native Ads

**Platforms**

iOS

**Versions**

- Android:
- iOS: 13.2
- react-native-fbads: 6.3.0
- react-native: 0.59.5

**Ads Environment**

- Facebook app installed: Yes
- Happens in test (dev build + device is marked as a test device): Yes
- Happens in production (release build + **not** a test device): Not released yet
- Facebook review status: approved

**Current Behaviour**

Rendering a NativeAd multiple times in the same ListView shows the same ad.

**Expected Behaviour**

I expect to see different ads.

**Steps to Reproduce**

Render 2 NativeAds in a ListView.

**Additionals**

**Comment by frankied003** [comment]
Were you able to solve this? Same thing here. I call new nativeAdsManager with the placement ID to get the new ad, but that makes it glitchy since I can't await that...

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
