### ISSUE TITLE
Interstitial Ads

### ISSUE THREAD

**Issue by ngocsang103** [callstack/react-native-fbads#236]
how to preload ads before show ads in react native fbsdk?
I want to preload the interstitial ads before show it. please help me.

**Comment by Jhonte** [comment]
+1  Just installed this and so far it's working great.  But there is a slight delay every time.

**Comment by ngocsang103** [comment]
> +1 Just installed this and so far it's working great. But there is a slight delay every time.

it will long delay for video. it will better if i can preload the ads before show it

**Comment by Jhonte** [comment]
@ngocsang103 https://github.com/callstack/react-native-fbads/pull/237 Think I got it it to work properly.  But I've never touched native code before so let's wait and see :D

**Comment by ngocsang103** [comment]
> @ngocsang103 #237 Think I got it it to work properly. But I've never touched native code before so let's wait and see :D

Thank you for support.
But I test  only for android but i get errore. I use the same code in https://github.com/callstack/react-native-fbads/blob/1b3d7f761a1e646f5c42ea1323158ae8763196e5/android/app/src/main/java/suraj/tiwari/reactnativefbads/InterstitialAdManager.java
and then use the file https://github.com/callstack/react-native-fbads/blob/c5610045d0cf28546afb08890f96744335ad1f50/src/InterstitialAdManager.ts in the react native 
error : 
TypeError: _reactNativeFbads.InterstitialAdManager.preloadAd is not a function. (In '_reactNativeFbads.InterstitialAdManager.preloadAd(_adsId.interPlaceId)', '_reactNativeFbads.InterstitialAdManager.preloadAd' is undefined)

please help me.

**Comment by Jhonte** [comment]
Think you need to wait for the pull request to be validated and then a new release. I ran `yarn tsc` so that the file `dist/lib/InterstitialAdManager.js` had the correct functions as well.   If you need it work asap add this into the above path and try again.

`import { NativeModules } from 'react-native';
const { CTKInterstitialAdManager } = NativeModules;
export default {
    /**
     * Shows interstitial ad for a given placementId
     */
    showAd(placementId) {
        return CTKInterstitialAdManager.showAd(placementId);
    },
    /**
     * Preloads an interstitial ad for a given placementId
     */
    preloadAd(placementId) {
        return CTKInterstitialAdManager.preloadAd(placementId);
    },
    /**
     * Shows an already preloaded Ad
     */
    showPreloadedAd(placementId) {
        return CTKInterstitialAdManager.showPreloadedAd(placementId);
    }
};`

**Comment by jawkhan** [comment]
The above didn't work for me.
When I install react-native-fbads, it looks like I'm installing an outdated version

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
