### ISSUE TITLE
InterstitialAdManager.showAd error after calling multiple times

### ISSUE THREAD

**Issue by grean** [callstack/react-native-fbads#240]
I'm aware of this issue and related PR https://github.com/callstack/react-native-fbads/issues/36
But it doesn´t fix the problem entirely because in my UI i have a caroussel and in each item, i can call InterstitialAdManager.showAd() to unlock some kind of content.
When i simulate a user that call showAd on the first item, then scroll to the next item and rapidly call showAd on it, i have this error : 
![Simulator Screen Shot - iPad (7th generation) - 2020-01-25 at 10 50 07](https://user-images.githubusercontent.com/170967/73119527-7b3b0880-3f63-11ea-8717-30f5ea77942c.png)
How can i catch the error ? i tried with a try catch but no success.. I also need to avoid "controled" behavior with parent element because it will breaks performence on flatList in the caroussel..
Using 
"react-native-fbads": "^6.3.1",
System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 179.23 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by grean** [comment]
On android the error seems to be catch but in ios the error is still there.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
