### ISSUE TITLE
Interstitial crash

### ISSUE THREAD

**Issue by Pingou** [callstack/react-native-fbads#241]
Crashlytics notifies me of a production crash on iOS (13.3):

EXC_BAD_ACCESS KERN_INVALID_ADDRESS in EXInterstitialAdManager interstitialAdDidClose

Is anybody else experiencing this issue?

React Native 60.5
Facebook Review status: approved

**Comment by tmjordan** [comment]
Hey @Pingou , i have exactly the same problem. Did you find a solution or any workaround? Thanks for your help

**Comment by Pingou** [comment]
@tmjordan Unfortunately no, as I removed fb ads in my apps for unrelated reasons.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
