### ISSUE TITLE
native banner without MediaView is not clickable

### ISSUE THREAD

**Issue by bougarfaoui** [callstack/react-native-fbads#242]
# Bug Report
Thanks for this amazing repo , I tried to create a native banner using ```WithNativeAd``` function but the problem when I removed the MediaView component , the native banner is not clickable and when I put it back the native banner is clickable. 
```
      <View style={{ flexDirection: 'column', margin : 0, position : 'relative', borderRadius : 3, overflow : 'hidden'}}>
        <View style={{ flexDirection: 'row', }}>
          <View style={{margin : 5 }}>
           <AdIconView   style={{ width: 60, height: 60,borderRadius : 3 ,}} />
          </View>
          <View
            style={{flexDirection: 'row', justifyContent : 'space-between', flex : 1 ,paddingRight: 5,paddingVertical: 5, 
            borderBottomWidth : 1, borderBottomColor : 'rgba(0,0,0,0.05)',
            borderTopWidth : 1, borderTopColor : 'rgba(0,0,0,0.05)' }}
          >
            <View
              style={{ flexDirection: 'column',  flex: 1, paddingLeft : 5,paddingRight : 2 }}
            >
                <Text numberOfLines={1} style={{height : 20, }}>
                  <TriggerableView style={{ fontSize: 16,  }}>
                      {this.props.nativeAd.headline}
                  </TriggerableView>
                </Text>
               <TriggerableView numberOfLines={2} style={{ color : 'rgba(0,0,0,0.5)'}}>
                {this.props.nativeAd.socialContext}
              </TriggerableView> 
            </View>
         

            <View style={{ alignItems: 'center', width : 100, height : 36,marginTop : 20,  borderRadius : 3, }}>
              <TriggerableView
                style={{
                  fontSize: 14,
                  width : '100%',
                  textAlign : 'center',
                  fontWeight : '700',
                  lineHeight : 36,
                  height : 36,
                  color: '#fff',
                  borderTopWidth: 0,
                  borderRadius : 3,
                  backgroundColor : '#ff3838',

                }}
              >
                {this.props.nativeAd.callToActionText}
              </TriggerableView>
            </View>
          </View>
        </View>
        <AdChoicesView location="topRight" expandable={true} style={{ position: 'absolute', right: 0, top: 0,backgroundColor : 'red' }} />
        <Text style={{color : 'rgba(0,0,0,0.23)', position : 'absolute', top : 0, right : 30, height : 20, lineHeight : 20, fontSize : 13, }}>Ad</Text>
      </View>
```
According to facebook docs MediaView is mandatory for Native Ad and is not mandatory in native banner.

is there a workaround for that ? 

**Before opening**

- [ Yes] Did you try the latest release?
- [No ] Did you look for existing issues?

**Ad Modules**
Native Ads

**Platforms**
iOS

**Versions**

- iOS: 13
- react-native-fbads: 6.3.0
- react-native: 0.61.5

**Ads Environment**

- Facebook app installed: yes
- Happens in test (dev build + device is marked as a test device):yes
- Happens in production (release build + **not** a test device):yes
- Facebook review status: approved

**Comment by RudyLu** [comment]
I was hit by this issue as well.
Does anyone know how to resolve or any way to workaround?

**Comment by Suraj-Tiwari** [comment]
Just add a Blank media video without any height width. It will work.

**Comment by RudyLu** [comment]
@Suraj-Tiwari, thanks for the tip.
Yes I tried to workaround as you suggested but with no luck,

```        
<MediaView style={{ width: 0, height: 0 }} />
```
Also not working when setting the width/height as 10.

--
The same code works when specifying the width/height as `50`, so I would assume my implementation is ok.

**Comment by Suraj-Tiwari** [comment]
Can you please push demo code on a repo so i can have a look?

**Comment by RudyLu** [comment]
I just tried to reproduce this with `example/`, however I cannot get it running.

**Comment by RudyLu** [comment]
I just created sample app that should be able to reproduce this issue,
https://github.com/RudyLu/react-native-fbads-example

@Suraj-Tiwari, could you please help give it a try?

Thanks in advance.

**Comment by Suraj-Tiwari** [comment]
Sure I'll have a look

**Comment by aarnavcurefit** [comment]
Just add <MediaView style={{ width: 1, height: 1 }} />

**Comment by aarnavcurefit** [comment]
try this <MediaView style={{ width: 1, height: 1 }} />

**Comment by tirrth** [comment]
Adding <MediaView style={{ width: 1, height: 1 }} /> to the NativeAdComponent works just fine for me!! Thanks...

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
