### ISSUE TITLE
Test ads working but live ads stuck at requesting.  What am I missing?

### ISSUE THREAD

**Issue by mochi08** [callstack/react-native-fbads#243]
I am using RN v0.61, and just trying to integrate a simple fb banner ads at bottom of my app screen.  I've setup my Android app in fb developer acct which gave me an App ID and added Audience Network as a product.  I've got my app approved for fb monetization, and have the Placement ID.

Following the documentation, I installed react-native-fbsdk.  Since I'm on RN 0.61, I skipped the linking part.  The only thing that I added in my code to initialize fbsdk is adding the following in AndroidManifest.xml:
`<meta-data 
        android:name="com.facebook.sdk.ApplicationId"
        android:value="@string/facebook_app_id"/>`

Next I installed react-native-fbads (again skipping the linking).  Then in my App.js I added the banner like this:
`<BannerView
          placementId="My_PlacementID"
          type="standard"
          onPress={() => console.log('click')}
          onLoad={() => console.log('loaded')}
          onError={err => console.log('error', err)}
        />`

I added my phone's AAID in the Test Devices and the ads were showing correctly.  I assume this means that I implement it correctly, so I set everything to go live and published my app.  It's been about a week and I have not got any ads except on test device.  The Audience Network Status for the property is stuck at "Reqesting ads". 

Anybody got the ads to work?  Can you tell what I am missing in my implementation, or suggest something to try?  Thanks!

**Comment by huynhvanquy** [comment]
Could you share me step by step config it or not? Because i am trying to config so it's not yet finished.
Now my device run and stop app.

**Comment by mochi08** [comment]
@huynhvanquy have you got yours to work?  I still haven't figured out mine yet.

Anyway, here's my steps in the setup:
** Facebook Developer **
- Create an app for my Android app in facebook developer account, which gives me the App ID
- Add Audience Network under Products
- Filled the required info, including the Goolge Play package name, Class Name (MainActivity), and key hashes (hopefully I got the key hashes right).  Added business info but it's not verified
- Did not fill in the Data Protection Officer Contact Information, doesn't seem to be required.
- Turn on go live

** Facebook Monetizing Manager **
- Create a property for the Android app, had it reviewed and approved
- Create banner ad space, which gives me the Placement ID
- For test ad, I added the AAID under "Integration - Testing" menu.

** React Native **
- Install react-native-fbsdk with yarn add.  Only thing I added are the "facebook_app_id" in string.xml with my App ID, and the "meta-data" tag for com.facebook.sdk.ApplicationId in AndroidManfiest.xml.  
- Install react-native-fbads.
- In App.js, add improt {BannerView} from 'react-native-fbads', and add the <BannerView> with my placementId.

Ads are showing in test device only.  Actual device running the app is not showing any ad.  In Monetizing Manager, it shows there are requests but there is no fills.

I did skip the "AudienceNetworkAds" codes in the MainActivity.  I thought it is not necessary with RN 0.6+.  Maybe I am wrong.  I am going to try add those codes to MainActibity.java to see if it makes a difference.

**Comment by hend-elsahli** [comment]
Hey @mochi08 , did you find a solution?

**Comment by neghani** [comment]
Hey, @mochi08 did you find solution?

**Comment by lewatt23** [comment]
any solutions far?

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed /explained ,clarified (in the readme or example )yet then please reopen it.

**Comment by huseyintamer** [comment]
Same problem: Test ads working but live ads stuck at requesting

Packages:
"react-native": "0.63.3",
"react-native-fbads": "^7.0.5",
"react-native-fbsdk": "^3.0.0",


![Ekran Resmi 2021-05-13 01 15 05](https://user-images.githubusercontent.com/8278275/118051687-1854c700-b38a-11eb-9529-010ae37414f1.png)

![Ekran Resmi 2021-05-13 01 18 10](https://user-images.githubusercontent.com/8278275/118051734-299dd380-b38a-11eb-9845-e072336b4dbb.png)

**Comment by jasonnfeng** [comment]
@huseyintamer I have the same problem,do you have any solution?

**Comment by rohitpaniker** [comment]
I have the same problem, anyone got any solution yet?

**Comment by UsmanAlgoace** [comment]
getting the same problem for iOS, test banner ads are working, but stuck at Requesting Ads on production.
did anyone manage to solve it ?
