### ISSUE TITLE
compatibility with react-native 0.62

### ISSUE THREAD

**Issue by Thomazella** [callstack/react-native-fbads#244]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

yes

**Platforms**

yes

**Versions**

- Android:
- iOS:
- react-native-fbads: latest
- react-native: 0.62

**Ads Environment**

- Facebook app installed:
- Happens in test (dev build + device is marked as a test device): yes
- Happens in production (release build + **not** a test device):
- Facebook review status: [not submitted | approved]

**Current Behaviour**

after upgrading to react-native 0.62 I cant build android. Double checked everything and it seems correct. Could the auto linking files have changed?

```
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fbads:
          - None of the consumable configurations have attributes.
```

**Expected Behaviour**

should build android

**Steps to Reproduce**

If you install the library on a fresh react-native 0.62 project it wont build (confirmed)
**Additionals**

**Comment by huynhvanquy** [comment]
You can run and show ads test or not?

**Comment by Thomazella** [comment]
It doesn't build.

**Comment by andy-io** [comment]
i have the same issue as well

**Comment by hanjjang18** [comment]
i have save issue

**Comment by kirampark** [comment]
I have an issue as well

**Comment by apjinfosolution** [comment]
anyone find solution for this?

**Comment by ITLight** [comment]
i have same issue

**Comment by hussainarthuna** [comment]
I am having the same issue

**Comment by scaralfred** [comment]
I fixed this. Try to move these lines in => "android/settings.gradle" like this:

`rootProject.name = 'your_project_name'

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':react-native-fbads'
project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app')

build success

- I just moved "apply from... " from the bottom to the top.

**Comment by hussainarthuna** [comment]
> I fixed this. Try to move these lines in => "android/settings.gradle" like this:
> 
> `rootProject.name = 'your_project_name'
> 
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> 
> include ':react-native-fbads'
> project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app')
> 
> build success
> 
> * I just moved "apply from... " from the bottom to the top.

I tried, but it is not working. Thank you for your reply.

**Comment by Jhonte** [comment]
Same issue here as well, just upgraded to 0.62 :(

**Comment by Beyazatli** [comment]
I have that same problem.
I looked at all the issues in the repo, but I could not find a solution.
Any solution?

**NodeJS**: 10.20.1
**NPM**: 6.14.4

**ReactNative FBSDK**: ^1.1.1
**ReactNative FBADS**: ^6.3.1
**React Native**: ^0.62.0

**OS**: Windows 10, 1909

Output Screenshot: https://prnt.sc/sey9rj
Output Text:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fbads:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fbads:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 5s
```

**Comment by Jhonte** [comment]
No idea at all why, but changing the order and adding a `/` in the end of the path in settings.gradle seems to work for me.

```
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

include ':react-native-fbads'
project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')


```

**Comment by hussainarthuna** [comment]
> No idea at all why, but changing the order and adding a `/` in the end of the path in settings.gradle seems to work for me.
> 
> 
> 
> ```
> 
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> 
> include ':app'
> 
> 
> 
> include ':react-native-fbads'
> 
> project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')
> 
> 
> 
> 
> 
> ```

I confirm as it is working perfectly now.
Thank you so much.

**Comment by grean** [comment]
Is Someone can explain why in RN 0.62 we now have to add those lines in settings.gradle in order to make the build work ?
There is no mention of those lines nor in the package readme nor in the facebook tutorials mentionned in the package readme :(
Therefore, it works well. Thanks !

**Comment by Thomazella** [comment]
Yeah pretty big issue still, will try the solution suggested but IMO it's not a fix, until some official doc/version bump. If this lib isn't getting proper attention & maintenance I'd migrate away from it

**Comment by kkusanagi** [comment]
So does this mean react-native-fbads still need `react-native link react-native-fbads`? As the linking is deprecated for RN 0.60+

**Comment by Thomazella** [comment]
I don't know, luckily don't need to fix this right now

**Comment by aashish-choudhary** [comment]
> So does this mean react-native-fbads still need `react-native link react-native-fbads`? As the linking is deprecated for RN 0.60+

Yes It is or you could just paste these lines at the end to settings.gradle

include ':react-native-fbads'

project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')

**Comment by huzaima1298** [comment]
i tried every solution  but nothing helped. someone solved it

**Comment by huzaima1298** [comment]
> # Bug Report
> **Before opening**
> 
> * [x]  Did you try the latest release?
> * [x]  Did you look for existing issues?
> 
> **Ad Modules**
> 
> yes
> 
> **Platforms**
> 
> yes
> 
> **Versions**
> 
> * Android:
> * iOS:
> * react-native-fbads: latest
> * react-native: 0.62
> 
> **Ads Environment**
> 
> * Facebook app installed:
> * Happens in test (dev build + device is marked as a test device): yes
> * Happens in production (release build + **not** a test device):
> * Facebook review status: [not submitted | approved]
> 
> **Current Behaviour**
> 
> after upgrading to react-native 0.62 I cant build android. Double checked everything and it seems correct. Could the auto linking files have changed?
> 
> ```
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve project :react-native-fbads.
>      Required by:
>          project :app
>       > Unable to find a matching configuration of project :react-native-fbads:
>           - None of the consumable configurations have attributes.
> ```
> 
> **Expected Behaviour**
> 
> should build android
> 
> **Steps to Reproduce**
> 
> If you install the library on a fresh react-native 0.62 project it wont build (confirmed)
> **Additionals**

hey did something work for u?

**Comment by Thomazella** [comment]
@huzaima1298 have not fixed it as I don't need to. Sorry I can't be of much help.

**Comment by serhangursoy** [comment]
For some reason on me `react-native link react-native-fbads` links to 
`'../node_modules/react-native-fbads/android/` not to `'../node_modules/react-native-fbads/android/app/` which creates the main issue. Check the main path. Also changing order helped too

**Comment by neghani** [comment]
> No idea at all why, but changing the order and adding a `/` in the end of the path in settings.gradle seems to work for me.
> 
> ```
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> include ':app'
> 
> include ':react-native-fbads'
> project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')
> ```

The above solution work for me, I have no clue why is fixed at atll.

**Comment by akhzarna** [comment]
Still fighting for this, tried all above solutions nothing worked for me.

I am MAC user 

Can anybody help me or me should leave trying this

**Comment by akhzarna** [comment]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > No matching configuration of project :react-native-fbads was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.

can anyone help me ?

**Comment by kellvembarbosa** [comment]
Following the tip from @hussainarthuna I realised that mine was without / app:
`project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android')`

I put it at the end of the uri / app it looks like this:
`project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app')`

And it worked perfectly!

**Comment by thymikee** [comment]
We've released v7 today. Please upgrade :)

**Comment by yousafConovo** [comment]
Has anyone found a solution?
