### ISSUE TITLE
BannerView Ads Not Clickable

### ISSUE THREAD

**Issue by FlippingWork** [callstack/react-native-fbads#245]
I am using the latest version of this code on iOS and the BannerView ad links are not clickable... any reason?

**Comment by Jhonte** [comment]
https://github.com/callstack/react-native-fbads/commit/1b3d7f761a1e646f5c42ea1323158ae8763196e5 This worked for me.

**Comment by tmjordan** [comment]
@FlippingWork make you that your banner is not encapsulated by a TouchableOpacity component.
You must use a simple View

**Comment by tmjordan** [comment]
@FlippingWork make sure you that your banner is not encapsulated by a TouchableOpacity component.
You must use a simple View

**Comment by aarnavcurefit** [comment]
use <MediaView style={{ width: 1, height: 1 }} />
