### ISSUE TITLE
Interstitial is not full screen and crash

### ISSUE THREAD

**Issue by sbusayarat** [callstack/react-native-fbads#248]
# Bug Report

**Before opening**

- [X] Did you try the latest release?
- [X] Did you look for existing issues?

**Ad Modules**
Interstitial Ads

**Platforms**
iOS

**Versions**

- iOS: 13.4.1
- react-native-fbads: ^6.3.1
- react-native: 0.61.5

**Ads Environment**

- Facebook app installed: Yes
- Happens in test (dev build + device is marked as a test device): Yes
- Happens in production (release build + **not** a test device): Not released to prod yet
- Facebook review status: not submitted

**Current Behaviour**

A live interstitial ad shows up on my test device but it doesn't take the entire screen and I can pull it down immediately even though the ad has a count down timer.

![image](https://user-images.githubusercontent.com/8260870/83340207-3bc25700-a28a-11ea-9c89-8577b586e988.png)

And once I pull it down (instead of clicking on X button), the ad fails the load the next time.

![image](https://user-images.githubusercontent.com/8260870/83340216-4a107300-a28a-11ea-9ce6-09fe948cf3f0.png)

**Expected Behaviour**

The Ad should take the entire screen and cannot be pulled down.

**Steps to Reproduce**

I simply call `InterstitialAdManager.showAd`.   I use functional React if that makes a different. 

```
    useEffect(() => {
        InterstitialAdManager.showAd('XXXX)
            .then(didClick => {
                console.log('FB Ads Succeeded');
                console.log('didClick', didClick);
            })
            .catch(error => {
                console.log('FB Ads Error');
                console.log(error);
            });
    }, []);
```

Any help will be appreciated.  Thanks!

**Comment by scaralfred** [comment]
I also got this :(

**Comment by sbusayarat** [comment]
fyi, I fixed this by bumping the native library to the latest version.

In Podfile:
`pod 'FBAudienceNetwork', '5.9.0'`

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
