### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by LGLabGreg** [callstack/react-native-fbads#249]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

Banner Ads

**Platforms**

iOS

**Versions**

- Android:
- iOS: 9
- react-native-fbads: 6.3.1
- react-native: 0.61.2

Hi,

I submitted my app to the app store and it was rejected with the following reason:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

I looked into the archive (grep -r "UIWebView" .) and found fbads was using the class. Removed fbads from project and resubmitted and the app was approved.

Anyone found a solution to that? Any plans to update to WKWebView?

Thanks.

**Comment by LGLabGreg** [comment]
Fixed it by using FBAudienceNetwork 5.9.0, read me should be updated. With RN > 0.60 you don't even need to update the podfile.

**Comment by LGLabGreg** [comment]
Btw thanks for the hard work guys, was pretty easy to fix the above and apart from that everything is working perfectly!

**Comment by kostiantyn-solianyk** [comment]
Thank you @LGLabGreg saw your issue before publish with 5.1.0 version. So, I think you saved my some time.
