### ISSUE TITLE
[Suggest] Add Search Path Framework

### ISSUE THREAD

**Issue by congnguyen91** [callstack/react-native-fbads#25]
Please add search path framework in build setting for IOS like react-native-fbsdk for implementing FBSDK: 
$(PROJECT_DIR)/../../../ios/Frameworks

**Comment by sangotaro** [comment]
+1

**Comment by grabbou** [comment]
Hey - can you explain the reason for that? Just want to understand the use-case and how to test it's resolved. My example and all apps I've been working with work just fine.

**Comment by Suraj-Tiwari** [comment]
issue related to older version.
