### ISSUE TITLE
Native Ads refresh

### ISSUE THREAD

**Issue by devaar100** [callstack/react-native-fbads#255]
If we fetch 10 ads using ads manager - 
1. Is it legal to switch between ads when one is already being shown or only when there is error we can show another fetched ad ?
2. After what duration can ads be swapped ?
3. If a different ad is shown after this legal duration in the same native ad container are they considered 2 impressions or 1 ?

The documentation here and on FB website say nothing about all these and neither was FB support helpful. So please help me out. Thanks.

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been explained, clarified in the readme yet then please reopen it.
