### ISSUE TITLE
support to Audience Network SDK 6.0.0 

### ISSUE THREAD

**Issue by victorvhpg** [callstack/react-native-fbads#257]
Are there any plans to support Audience Network SDK 6.0.0  ?

https://developers.facebook.com/docs/audience-network/changelog-android#6_0_0

**Comment by whalemare** [comment]
Any comments here from authors, maybe?

**Comment by mrousavy** [comment]
The currently pinned version does not work at all, resulting in no ads showing up and no warnings or errors showing up (!). People who don't know about this issue will pull their hairs out.

I've upgraded to the SDK 6 and it looks like everything is working, but I'd feel more comfortable if the maintainers here would take a look at this, test this, and make an official release which supports the latest SDK.

**Comment by victorvhpg** [comment]
@mrousavy 
Please update the npm package with these new updates  (sdk 6)

**Comment by mrousavy** [comment]
@victorvhpg I wish I could! But I don't have permission for npm. cc @thymikee etc ???

**Comment by thymikee** [comment]
The project should be consumable through github. I'll see what can be done about the publishing next week. Sorry for the wait :)

**Comment by victorvhpg** [comment]
@thymikee thanks
