### ISSUE TITLE
Integration issues in react native version 0.63.2

### ISSUE THREAD

**Issue by adeel111** [callstack/react-native-fbads#258]
# Bug Report

**Before opening**

- [Yes] Did you try the latest release?
- [Yes] Did you look for existing issues?

**Platforms**

Android (issue):  Unable to find a matching configuration of project :react-native-fbsdk
iOS (issue):  Framework not found FBSDKCoreKit

**Versions**

- Android: 27
- iOS: 13.0
- react-native-fbads: 6.3.1
- react-native: 2.0.0

**Current Behaviour**

App is not running on both platforms android & iOS due to react-native-fbads lib configuration problems.

**Expected Behaviour**

react-native-fbads should be proper integrated in latest react native version so that app can run and Ads module can be tested

How to integrate this lib properly in react native 0.63.2?
Is it necessary to install react-native-fbsdk in order to use this lib?

Docs should be updated.

**Comment by mrousavy** [comment]
Yes you need ** react-native-fbsdk**.

Docs are updated and v7 will have full support for autolinking.

**Comment by thymikee** [comment]
We've released v7 today. Please upgrade :)
