### ISSUE TITLE
Could not resolve project :react-native-fbads

### ISSUE THREAD

**Issue by SaGaR1084** [callstack/react-native-fbads#259]
"react": "16.13.1",
 "react-native": "0.63.2",
 "react-native-fbads": "^6.3.1",
 "react-native-fbsdk": "^2.0.0",

show me this error after install:- `yarn add react-native-fbads`

<img width="575" alt="Screenshot 2020-10-11 at 1 19 52 AM" src="https://user-images.githubusercontent.com/34228088/95663863-4528cd80-0b60-11eb-8e9c-3e24df6ff67a.png">

**Comment by akhzarna** [comment]
Try changing your code from setting.graddle 

change this code 
include ':react-native-fbads'
project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android')

to this one

include ':react-native-fbads'
project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')

**Comment by mrousavy** [comment]
I think this will be fixed in v7 (https://github.com/callstack/react-native-fbads/pull/284)
