### ISSUE TITLE
Did not expect event target to be a number

### ISSUE THREAD

**Issue by hackrx** [callstack/react-native-fbads#261]
# Bug Report
When I am rendering ads, after loading 4 ads in an interval of 6 in Flatlist 
I am getting this error:
`Did not expect event target to be a number. Should have been a native component`
**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Steps to Reproduce**
I am rendering native ads and I have just used the given example.

**Additionals**
![image](https://user-images.githubusercontent.com/54453778/96727960-43b59b80-13d1-11eb-8787-6f3cfb715cb7.png)

**Comment by hackrx** [comment]
Also, I have just noticed that, when I scroll down, an Ad 1 at position 5 gets replaced with different ad (Ad 2), which is causing flatlist to re-render its items.
I have converted AdPost and Index to pureComponent but still, I am facing the issues. Why ads are replacing with another one when it is already displayed. A particular Ad is supposed to be at the position where it was earlier.
Please help me to resolve this issue.
Thanks.

**Comment by hackrx** [comment]
I just found that we can call `disableAutoRefresh()` to disable the autorefresh of ads, but it is giving an error

`Attempt to invoke virtual method 'void.com.facebook.ads.NativeAdsManager.disableAutoRefresh()' on a null object refrencec`

## index.js
```
import React, {PureComponent} from 'react';
import {NativeAdsManager, AdSettings} from 'react-native-fbads';
 
import NativeAdView from './AdPost';

AdSettings.clearTestDevices();
AdSettings.setLogLevel('none');
 

const nativeAdPlacementId = 'MyID';
const adsManager = new NativeAdsManager(nativeAdPlacementId);

adsManager.disableAutoRefresh();

export default class NativeAd extends PureComponent {
  render() {
    return (
      <NativeAdView
        adsManager={adsManager}
      />
    );
  }
}

```

**Comment by thymikee** [comment]
We've released v7 today with upgraded SDKs. Please try it out and see if this helps :)
