### ISSUE TITLE
[Error: no fill]

### ISSUE THREAD

**Issue by signorettif** [callstack/react-native-fbads#268]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

Interstitial Ads

**Platforms**

iOS 14 and iOS 13

**Versions**

- iOS: 13 // 14
- react-native-fbads: latest (6.3.1)
- react-native:  0.63.3

**Ads Environment**

- Facebook app installed: yes
- Happens in test (dev build + device is marked as a test device): yes
- Happens in production (release build + **not** a test device): not checked
- Facebook review status: approved

**Current Behaviour**

Interstitial ads show [Error: no fill] instead of being filled properly as expected. Additionally, the methods AdSettings.getTrackingStatus(); and AdSettings.setAdvertiserIDCollectionEnabled(true); are not found on the package at all

**Expected Behaviour**
Interstitial ad to show

**Comment by nenjamin2405** [comment]
I'm facing the same issue :(

**Comment by TMaszko** [comment]
Look at our updated readme about preparing simulator / device :)

**Comment by ShivamJoker** [comment]
@TMaszko can you please tell me whats the proper iOS setup, I followed readme and setup simulator as test device the ads are working in android but in iOS gives the same error as described above.

**Comment by gulsher7** [comment]
i'm facing same issue
