### ISSUE TITLE
Could not resolve project :react-native-fbads

### ISSUE THREAD

**Issue by Daniyalzakir321** [callstack/react-native-fbads#269]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :**react-native-fbads**.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fbads:
          - None of the consumable configurations have attributes.

**Comment by mrousavy** [comment]
I think this will be fixed in v7.

**Comment by TMaszko** [comment]
@Daniyalzakir321 It should be fixed now! Check out v7 :)
