### ISSUE TITLE
Could not resolve project :react-native-fbads

### ISSUE THREAD

**Issue by akhzarna** [callstack/react-native-fbads#271]
# Bug Report

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > No matching configuration of project :react-native-fbads was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

**Before opening**

- [ ] Did you try the latest release?
- [ ] Did you look for existing issues?

**Ad Modules**

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-fbads:
- react-native:

**Ads Environment**

- Facebook app installed:
- Happens in test (dev build + device is marked as a test device):
- Happens in production (release build + **not** a test device):
- Facebook review status: [not submitted | approved]

**Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

**Comment by TMaszko** [comment]
It is related to autolinking. Check out v7 :) It should be fixed !
