### ISSUE TITLE
Crash on iOS using AdChoiceView

### ISSUE THREAD

**Issue by PsykoSoldi3r** [callstack/react-native-fbads#286]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

Native Ads: AdChoicesView

**Platforms**

**Versions**

- Android: -
- iOS: 14
- react-native-fbads: 7.0.3
- react-native: 0.63.3

**Ads Environment**

- Facebook app installed: Yes and No
- Happens in test (dev build + device is marked as a test device): Both
- Happens in production (release build + **not** a test device): Yes
- Facebook review status: [not submitted | approved]: Not submitted

**Current Behaviour**

The ads are correctly displayed on Android device when I'm using the AdChoicesView component. On iOS it will crash when I'm using that component if I don't use it, there is no problem. I'm getting the following error in Xcode:

Error occurred in file AdChoiceView.m
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/2241262/109790405-aafe1a80-7c11-11eb-8e05-2512418d87bf.png">

**Expected Behaviour**

On iOS the AdChoicesView component should be displayed

**Steps to Reproduce**

I have just added the AdChoiceView component and it is crashing.

**Comment by frankied003** [comment]
Same exact problem here

**Comment by TMaszko** [comment]
Hi! Could you provide a link to the repository where we can easily reproduce the bug :)?. Thanks in advance !

**Comment by PsykoSoldi3r** [comment]
@TMaszko I would like to share but my repository is private. I'm going to make an example project in the weekend with this issue and put it into a public repository.

**Comment by frankied003** [comment]
Any update with this, still haven’t been able to figure it out.

**Comment by frankied003** [comment]
> @TMaszko I would like to share but my repository is private. I'm going to make an example project in the weekend with this issue and put it into a public repository.

Were you able to fix this issue? I'm still having it.

**Comment by TMaszko** [comment]
@frankied003 I'm waiting for the repo where I could easily reproduce the bug

**Comment by frankied003** [comment]
@PsykoSoldi3r Any update with this?

**Comment by PsykoSoldi3r** [comment]
@TMaszko Sorry for a late response. Have setup a clean react native project with the typescript template. Pushed the project to https://github.com/PsykoSoldi3r/ReactNative-FBAds-AdChoicesView-Issue

**Comment by frankied003** [comment]
Anyone have any luck with this. I tried changing packages around and playing with the AdChoiceView.m file but no luck.

**Comment by PsykoSoldi3r** [comment]
@TMaszko Do you have any updates on this issue?

**Comment by PsykoSoldi3r** [comment]
I'm trying to investigate a little bit what is going on. It seems like the location props value of AdChoiceView is not properly converted to UIRectCorner. When I'm setting the UIRectCorner hard coded on the line where the error occurred. The app won't crash and the AdChoiceView is displayed on iOS.

When I could find a solution for this I will let it know.

**Comment by PsykoSoldi3r** [comment]
@TMaszko Pull request is merged, when can we expect a new release?

**Comment by TMaszko** [comment]
@PsykoSoldi3r it is already available. I did it yesterday :)
