### ISSUE TITLE
preloadAd

### ISSUE THREAD

**Issue by nguyenthixanh18011988** [callstack/react-native-fbads#287]
hi author!

I use function preloadAd() in a class Flatlist and use showPreloadedAd() in another class FlatlistItem.
I want to call didclick in showPreloadedAd()  to go to detail screen in a FlatlistItem but didclick  just has in preloadAd().
please help me to solve it.

**Comment by nguyenthixanh18011988** [comment]
I want to call preloadAd() in home screen and call showPreloadedAd() in another screen, but if user close the ads,  the function will call in promised of preloadAd() not in showPreloadedAd()

**Comment by TMaszko** [comment]
Please provide a repo  where we can easily understand what's going on and with that we may be able to further help you. I'll close till then.
