### ISSUE TITLE
onError method for NativeAdsManager

### ISSUE THREAD

**Issue by rskull** [callstack/react-native-fbads#33]
onError method for NativeAdsManager. Is there plans to be implemented?

https://github.com/callstack-io/react-native-fbads/blob/master/src/ios/CTKNativeAdManager.m#L78

**Comment by grabbou** [comment]
Yup, as long as we know how to handle such case. Do you have any ideas how typical reference implementation could look like?

**Comment by Suraj-Tiwari** [comment]
related to older version
