### ISSUE TITLE
Why banner ads not shown

### ISSUE THREAD

**Issue by tiendq** [callstack/react-native-fbads#61]
I tried to show a banner for testing but there is only a blank banner at the bottom of screen. No ad at all.

Is there additional steps required to test ads?

Thanks,

RN code:
```
<BannerView
          type="standard"
          placementId="abc_xyz"
          onClick={() => console.log('click')}
          onError={(err) => console.log('error', err)}
/>
```

My placement for this banner (removed placement ID):

<img width="631" alt="screen shot 2017-05-23 at 2 47 32 pm" src="https://cloud.githubusercontent.com/assets/815910/26343640/027e6796-3fc7-11e7-80d2-75210c90e850.png">

**Comment by galcivar** [comment]
I have the same issue

**Comment by eahang** [comment]
I got blank ads for the first time but after reloading (without clear app in memory) it shows normally.
The error is show like this: 
![image](https://user-images.githubusercontent.com/15654092/35483697-c8dcc958-0477-11e8-800d-866cc55c8c07.png)

Do you know hoe to fix it?

**Comment by BeckZero** [comment]
+1 same here...

**Comment by GOLFJT** [comment]
add AdSettings.addTestDevice(AdSettings.currentDeviceHash) your code

**Comment by gesf** [comment]
I am also having that proxy issue...

**Comment by kkusanagi** [comment]
I'm not sure also. 

In DEBUG mode, it did not show anything. need add code as below.

```
AdSettings.clearTestDevices();
AdSettings.addTestDevice(device_id);
```
The device_id, you can find it through the log. it will mention you to this code with your device hash id. 
Oh, the AdSettings. currentDeviceHash did not work.

In RELEASE mode, it did show the ads. Try put your apps to LIVE status in facebook developer page.

Still cannot? Then you need to add below into build.gradle
```
dependencies {
  ...
  compile 'com.facebook.android:audience-network-sdk:4.+'
}

```

**Comment by teyou** [comment]
my BannerView is not showing anything too. :(

**Comment by leokaessner** [comment]
Same here. Only works on devices where I'm logged in with my facebook account. For all others I get a huge increase of CPU and memory usage and app freezes

**Comment by jaronsmith2006** [comment]
Any solution with that proxy error ?
Test ad works for 1-2 times. then after it suddenly stopped working. Any correct sample code to implement facebook ad will help.

**Comment by jaronsmith2006** [comment]
@eahang any solution you found ?

**Comment by eahang** [comment]
@jaronsmith2006 Now it works as normal. 
in render function add **InterstitialAdManager**
`InterstitialAdManager.showAd(PLACEMENT_ID)`

```
<BannerView
       placementId={PLACEMENT_ID}
       type="standard"
        onError={err => {
              console.log(err);
        }}
 />
```

**Comment by erandagan** [comment]
The latest version of this package should be working. If you're still having trouble, please open a new issue with full reproduction. Thanks!

**Comment by shradhdhaVek** [comment]
Banner ads not show in react native android

**Comment by babarbahadur** [comment]
Banner ads does not show in react native android as shows following error
![screenshot](https://user-images.githubusercontent.com/48913440/105630457-33e3a280-5e6b-11eb-96a5-15c0efc84b2a.PNG)

**Comment by lbneves93** [comment]
I got the same error. In my case was cause I'm trying to show a Banner Ad, but using a placementId from an Interstitial Ad.
