### ISSUE TITLE
Warning: Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by tomasfrancisco** [callstack/react-native-fbads#63]
I'm getting this warning, referring to the file `withNativeAd`. Perhaps it's referring to the timeout presented in `NativeAdsManager` within the method `onAdsLoaded`. But I don't really have a solution to help with.

Just leaving here the screenshot so can anyone track the warning.

![simulator screen shot 9 jun 2017 10 30 39](https://user-images.githubusercontent.com/4301103/26970117-08217530-4d00-11e7-8900-806087807f82.png)

**Comment by asgvard** [comment]
Have the same issue.
I have a FlatList (that sometimes unmounting the Views that are far away from scroll position), and I have few FB Ads in the "Feed". All of them are using the same "adsManager", which basically fires the same "onAdsLoaded" event, and seems that this doesn't get called in time:
```javascript
  componentWillUnmount() {
    this.removeSubscription();
  }
```
In result a FB Ad still receives this "onAdsLoaded" event on Unmounted component which gives this warning.

**Comment by michaelspeed** [comment]
i am currently having the save issue. sometimes i even cannot to the end of the list. its starts looping

**Comment by Un3qual** [comment]
Could this be solved by just removing [this line](https://github.com/callstack-io/react-native-fbads/blob/master/src/withNativeAd.js#L58)?

**Comment by perrosnk** [comment]
Has anyone found any solution to this?

**Comment by erandagan** [comment]
Closing as this issue is referring to an old version of this package. If you encounter it after upgrading to the latest version, please open a new issue with reproduction.
