### ISSUE TITLE
Investigate what needs to be done for scoping in Expo

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-fbads#74]

**Comment by grabbou** [comment]
One of the potential solutions is to extend a module and override it with added methods. It's needed to scope ads to experiences.

**Comment by grabbou** [comment]
@wojteg1337 would be great if you could check what's the difference. Happy to explain any nuances of Expo SDK.

**Comment by erandagan** [comment]
Is this issue still relevant? Expo has [FacebookAds](https://docs.expo.io/versions/latest/sdk/facebook-ads) based on an older version of this library.

**Comment by Suraj-Tiwari** [comment]
Anyone had a talk with expo about this?

**Comment by Trancever** [comment]
Once lib is stable we can talk with them about new version.
