### ISSUE TITLE
'rectangle' option in BannerView doesn't work on iOS

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-fbads#76]
https://snack.expo.io/SJn-I15Pb

**Comment by efstathiosntonas** [comment]
Same here, it seems that the width of the view is always `1` no matter what i set to the view/banner width size.

**Comment by toandk** [comment]
Currently workout solution: modify these line in the file `node_modules/react-native-fbads/src/ios/CTKBannerView.m`:
```
adView.frame = CGRectMake(0, 0, adView.bounds.size.width, adView.bounds.size.height);
  adView.delegate = self;
```
to this:
```
adView.frame = CGRectMake(0, 0, adView.bounds.size.width, adView.bounds.size.height);
adView.autoresizingMask = UIViewAutoresizingFlexibleWidth;
adView.delegate = self;
```

**Comment by satya164** [comment]
@toandk can you send a PR with the change?

**Comment by toandk** [comment]
you can use my repo: https://github.com/toandk/react-native-fbads

**Comment by erandagan** [comment]
This issue is quite old and references an old version of this package. BannerView should be working as expected with the current version.
