### ISSUE TITLE
[Question] how to display ads inline a list view every x items?

### ISSUE THREAD

**Issue by efstathiosntonas** [callstack/react-native-fbads#79]
I have a FlatList currently showing hundreds of items with pagination and infinite  scroll. How it's possible to show ads every x items inside the list? Reddit and 9gag app is doing this.

Thanks

**Comment by omeraplak** [comment]
Hello @efstathiosntonas ,
You can implementation with renderRow of FlatList function. 
Example, your pagesize 20, you can add if your renderRow index is index % 20 === 0, you can insert native ad component.

**Comment by perrosnk** [comment]
@efstathiosntonas Have you found a solution to this? Would it be possible to share some code on how to achieve this?

**Comment by efstathiosntonas** [comment]
@perrosnk Sure, here's a gist i just created: https://gist.github.com/efstathiosntonas/0865256fa8e0a97a586a377b52b6fc5e
