### ISSUE TITLE
Error: No fill Android

### ISSUE THREAD

**Issue by munkhorgil** [callstack/react-native-fbads#80]
Ads can't work on Android

`Error: No fill
    at createErrorFromErrorData (NativeModules.js:117)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:354)
    at MessageQueue.js:129
    at MessageQueue.__guard (MessageQueue.js:269)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:128)
    at debuggerWorker.js:72`

Even I added below code
AdSettings.addTestDevice(AdSettings. currentDeviceHash);

My emulator has fb app installed

@satya164  Could you help me with it?

**Comment by wojteg1337** [comment]
cc @satya164

**Comment by munkhorgil** [comment]
I just solved this by putting hash id instead of `AdSettings.currentHashId`
Get the hash id from your android studio log.

**Comment by perrosnk** [comment]
@munkhorgil When changing to `deviceHashedId.equals("current") ` the app crashes on device running Android 4.4. Do you experience the same problem?
