### ISSUE TITLE
Doesn't work with FBAudienceNetwork-4.26.0 for iOS

### ISSUE THREAD

**Issue by 7kfpun** [callstack/react-native-fbads#81]
<img width="400" alt="screen shot 2017-09-16 at 3 28 55 pm" src="https://user-images.githubusercontent.com/2672802/30510388-67e4bb4c-9af5-11e7-9961-e6db39ac12d5.png">

**Comment by risto1913** [comment]
![skjermbilde 2017-09-25 kl 15 48 07](https://user-images.githubusercontent.com/501772/30811613-f8905a10-a208-11e7-8af6-8caafd237608.png)

I'm having the same issue.

I have tested the following:
1. pod install  (with: pod 'FBAudienceNetwork')
2. installed FBAudienceNetwork.framework into Frameworks and referenced it this way.
3. added it to Documents/FacebookSDK and referenced it to my disk

I can not get this to work.
Other PODs installed have worked nicely.

Any one else having this issue?

PS: I'm using Xcode 9.

**Comment by Anu-Ujin** [comment]
i m having this issue too,, is there anyone resolve this? @risto1913 @7kfpun

**Comment by wojteg1337** [comment]
@dratwas can you look at this ?

**Comment by dratwas** [comment]
@wojteg1337 I will. I'm able to reproduce this so i hope i will find time to take care of it.

**Comment by ianlin** [comment]
Have the same issue here.

**Comment by omeraplak** [comment]
Have the same issue here.

**Comment by yassy000** [comment]
is it related to below issue?
```
When importing FBAudienceNetwork SDK v4.26, you will get an error saying "No Such Module". To fix this issue, you need to rename FBAudienceNetwork.modulemap to module.modulemap in FBAudienceNetwork.framework/Modules folder. This will be fixed in the next release.
```

https://webcache.googleusercontent.com/search?q=cache:aZ4GvdZbf_QJ:https://developers.facebook.com/docs/audience-network/ios/+&cd=1&hl=ja&ct=clnk&gl=jp

But .. I could not find FBAudienceNetwork.modulemap at the directory. There was a module.modulemap already..

**Comment by yassy000** [comment]
for tmp, I've Installed 4.25.0 manually to ~/Documents/FacebookSDK and it works..

**Comment by omeraplak** [comment]
@yassy000 or you can install with Pod. I think is not good practice using Documents folder for framework references. 
https://cocoapods.org/

**Comment by wojteg1337** [comment]
tomorrow we have meeting about fb-ads so will take care about this issue

**Comment by alfredoreduarte** [comment]
FB included this at the "Known issues" section. It fixed it for me.

> When importing FBAudienceNetwork SDK v4.26, you will get an error saying "No Such Module". To fix this issue, you need to rename FBAudienceNetwork.modulemap to module.modulemap in FBAudienceNetwork.framework/Modules folder. This will be fixed in the next release.

**Comment by perrosnk** [comment]
Any updates on this? I am getting the same error.
I have also tried updating to v.4.27.2 but still I am getting the error

**Comment by perrosnk** [comment]
I think I found the problem, at least, it fixed it for me:
At `rn-fbads.xcodeproj` > `Build Settings` > `Framework Search Paths` I could only find `~/Documents/FacebookSDK`, which didn't correspond to the correct path where `FBAudienceNetwork` is installed when using Pod. So I added the path `$(PROJECT_DIR)/../../../../ios/Pods/FBAudienceNetwork` and it worked!

**Comment by perrosnk** [comment]
@7kfpun I think this issue should be closed, right?
