### ISSUE TITLE
ad imp is strangely smaller than request

### ISSUE THREAD

**Issue by yassy000** [callstack/react-native-fbads#83]
I've implemented fbads and released a few days ago.
The ads are seems showed correctly, but ads imp is small than expected.

Is there someone knows same issue?? and how to solve it?
Thanks 

![image](https://user-images.githubusercontent.com/5616913/32083971-880a1382-bb01-11e7-96e7-5d005e37a7fb.png)

**Comment by Rebsos** [comment]
I have the same problem, did you solved this?

**Comment by rwitcher** [comment]
Bumping this up.  I'm seeing the same.  I'm using via expo.  Any resolution?

**Comment by erandagan** [comment]
> Bumping this up. I'm seeing the same. I'm using via expo. Any resolution?

Please submit an example of your usage. Are you using native / banner / interstitial ads?

**Comment by Suraj-Tiwari** [comment]
First of all that for old version second facebook use heavy target filtering (age,gender,region,profession,recent likes and 50 others filters)  so that can be a factor.
