### ISSUE TITLE
Selection of clickable zones in native ads

### ISSUE THREAD

**Issue by BorisMisnik** [callstack/react-native-fbads#86]
Facebook [guidelines](https://developers.facebook.com/docs/audience-network/policy?locale=en_US#control) does not allow to have white spaces clickable on native ads. The current implementation doesn't let us to select clickable zones on native ads. We need an option to add clickable elements to this method [nativeAd registerViewForInteraction]. 
We'll be very grateful for any help on this issue.

**Comment by liubomyrp** [comment]
I have the same issue on my side.

**Comment by perrosnk** [comment]
Any updates on this? Or anyone found any other solution?

**Comment by leo7r** [comment]
Same issue here, anyone with a solution?

**Comment by erandagan** [comment]
Use `TriggerableView` to select which views should react to interactions.
