### ISSUE TITLE
Unsupported top level event type "onLoggingImpression" dispatched extractEvents - React Native

### ISSUE THREAD

**Issue by gaphu** [callstack/react-native-fbads#87]
### Please help this error pops up every time banner loads, which loads successfully but i think ad impressions aren't working.

![screenshot_1515794882](https://user-images.githubusercontent.com/26577026/34897342-974d84ce-f813-11e7-8456-e0f9eead9404.png)

**Comment by roshanpal** [comment]
I have the exact same issue whenever the banner loads this pops up. For some reason if the banner didn't load, I don't see this error message.

**Comment by khalid283** [comment]
@gaphu @roshanpal Did you found any solution?

**Comment by efleurine** [comment]
I just make a pull request which I think resolve the problem @khalid283 @gaphu @roshanpal 

The solution was to add to `onLoggingImpression` in `getExportedCustomDirectEventTypeConstant` of `BannerViewManager` where the custum events are defined.

The onLoggingImpression was missing.

**Comment by efleurine** [comment]
@roshanpal My banner were loading even if I saw the error.
Try my fix to see if your banner are still not loadin. 
Thanks

**Comment by kkusanagi** [comment]
Yes, it works with no error for now.
Some explanation for those who want to edit.

Go to [Your Project]/node_modules/react-native-fbads/src/android/src/main/java/io/callstack/react/fbads

Edit BannerViewManager.java

Replace Code as below on same place

```
@Override
  public @Nullable Map getExportedCustomDirectEventTypeConstants() {
    return MapBuilder.of(
      "onAdPress",
      MapBuilder.of("registrationName", "onAdPress"),
      "onAdError",
      MapBuilder.of("registrationName", "onAdError"),
      "onLoggingImpression",
      MapBuilder.of("registrationName", "onLoggingImpression")
    );
  }
```

Save and rerun "react-native run-android" to recompile again. should fix now.

**Comment by rogerkerse** [comment]
I get the same error when using FacebookAds on Expo app and there I cannot edit native code

**Comment by Trancever** [comment]
@efleurine @khalid283 Did the pull request solve the issue?

**Comment by khalid283** [comment]
@efleurine @Trancever 

Yes, it working. 

I have also checked impression.

Thanks

**Comment by Trancever** [comment]
@khalid283 Great!
