### ISSUE TITLE
Error when building a release APK - Android

### ISSUE THREAD

**Issue by ianataffinity** [callstack/react-native-fbads#91]
I am using Mobile Center to build release APK's and its suddenly failing to complete a release build with this error:

    Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
        > Could not resolve project :react-native-fbads.
        Required by: project :app
            > Unable to find a matching configuration of project :react-native-fbads: None of the consumable configurations have attributes.

Any idea on how I can resolve this one?

Edit: It does work OK in a debug build.

**Comment by apjinfosolution** [comment]
how do you solve this error?

**Comment by apjinfosolution** [comment]
how did you solve this error?

**Comment by wassimbrsimo** [comment]
i got the same issue
