### ISSUE TITLE
Support cocoapods 1.4.0

### ISSUE THREAD

**Issue by Porshe** [callstack/react-native-fbads#92]
Please add `s.static_framework = true` to podspec file.

**Comment by toandk** [comment]
you can try installing the library manually as the instruction here: https://facebook.github.io/react-native/docs/linking-libraries-ios.html. Note, after installing the library, you have to remove the line `pod 'ReactNativeFBAds', :path => '../node_modules/react-native-fbads'` inside Podfile

**Comment by Porshe** [comment]
Yes, I know this but it is a workaround.

**Comment by Trancever** [comment]
@Porshe Could you make a pull request?

**Comment by erandagan** [comment]
This is no longer relevant I believe

**Comment by abhaynpai** [comment]
Hey @erandagan 

I think this needs to be done now cause React Native 0.60.x works on a podfile basis. So we need to have `podspec` specified in the project. I have upgraded my project and I am trying to build but I am facing an issue mentioned in #212 

So what's the best way to move ahead. Any ideas?
