### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by rogerkerse** [callstack/react-native-fbads#94]
So just implemented this plugin. I get test add and real add only on iOS Simulator. Everywhere else I get out of memory exception. Memory and CPU just keep climbing and all the buttons are unresponsive in the app. The problem comes, when I add BannerView to screen. I use latest versions of everything.

**Comment by doobix** [comment]
Similar situation here. My react-native app becomes unresponsive in the iOS simulator when I add the `BannerView` component. No problems when running it through Expo on my real phone though.

**Comment by erandagan** [comment]
This is an old issue which uses an outdated version of this package. If you're still having trouble with the newest version, please open a new issue and provide reproduction steps.

**Comment by AB91189** [comment]
still facing this issue. the application hangs in both platforms whenever i go to the page where there is a banner ad
