### ISSUE TITLE
Update installation guide

### ISSUE THREAD

**Issue by RyszardRzepa** [callstack/react-native-fbads#97]
Hi, 

I tried to install `react-native-fbads`  in existing and new project, but I could not get rid of the error:

> Include of non-modular header inside framework module 'FBAudienceNetwork': '/Users/ryrz01/Downloads/solapp/ios/Pods/Headers/Public/FBAudienceNetwork/FBAudienceNetwork/FBAdSize.h'
> 

I have FBAudienceNetwork.framework in the project directory Libraries/ , and  folder FacebookSDK in on my mac in /Documents directory. 

Does anyone know about any tutorial on how to add `react-native-fbads` to react native project?
Just installing the package will not work, or installing `FBAudienceNetwork` with cocopods. 

I had also issues on Android but this is a different case.

**Comment by Trancever** [comment]
Try to put FBAudienceNetwork inside FacebookSDK for iOS.

**Comment by RyszardRzepa** [comment]
@Trancever are u thinking about directory ?

 `Libraries/RCTFBSDK.xcodeproj/Frameworks`

**Comment by RyszardRzepa** [comment]
In the end I found out at I have to add` librn-fbads.a` to Link Binary With Libraires.
I also used cocopods to install FBAudienceNetwork.
![screen shot 2018-05-02 at 15 32 19](https://user-images.githubusercontent.com/13038459/39526149-355a4692-4e1e-11e8-8029-db78d5364042.png)
![screen shot 2018-05-02 at 15 32 37](https://user-images.githubusercontent.com/13038459/39526150-3589226e-4e1e-11e8-82d9-57a411c3af98.png)

**Comment by Trancever** [comment]
Did you follow this getting started guide for iOS - https://developers.facebook.com/docs/ios/getting-started ? In step 3 you have to drag those libraries from FacebookSDK directory to XCode project Frameworks group (if you don't have Frameworks group, create it). Also do it for FBAudienceNetwork.framework.

Btw. we are currently working on reimplementing this library from scratch. Current version is a bit out of date and we hope the next version will be much easier to configure and use.

**Comment by younes200** [comment]
None of this guides works, draging those libraries from FacebookSDK or the solution suggested by @RyszardRzepa with cocopods. 
Please provide a clear install procedure otherwise it's a wast of time trying to figure out how to linking those peace together...
