### ISSUE TITLE
Ads not showing up in Release version of the app

### ISSUE THREAD

**Issue by sajjanbalar** [callstack/react-native-fbads#99]
Hi, 

I am using the native ad component to create an ad in my home screen. My app uses the following:
                "react": "16.0.0-beta.5",
		"react-native": "0.49.3",
		"react-native-fbads": "^4.2.2",
		"react-native-fbsdk": "^0.7.0".

The code which I am using to create the ad is very similar to the example.
However, I can see the ad in my app only during debug.

**Comment by Trancever** [comment]
Can you provide sample code and show the error that you got?

**Comment by sajjanbalar** [comment]
export const SmallRowAd = withNativeAd(({ nativeAd }) => (
  <View style={styles.container}>
    {nativeAd.icon && (
      <Image style={styles.icon} source={{ uri: nativeAd.icon }} />
    )}
    <View>
      <Text numberOfLines={2} style={styles.title}>{nativeAd.title}</Text>
      {nativeAd.subtitle && (
        <Text numberOfLines={1} style={styles.subtitle}>{nativeAd.subtitle}</Text>
      )}
      <Text style={[styles.ad]}>Ad</Text>
      {nativeAd.description && (
        <Text numberOfLines={2} style={styles.description}>{nativeAd.description}</Text>
      )}
      <View>
        <Text style={styles.button}>{nativeAd.callToActionText}</Text>
      </View>
    </View>
  </View>
));

This is my ad component and I am using the same in my home screen link this:

import { NativeAdsManager } from 'react-native-fbads';
const adsManager = new NativeAdsManager('30310892021-445444444485'); 
<SmallRowAd adsManager={adsManager} />

**Comment by Trancever** [comment]
Code looks fine. I am thinking about configuration of your facebook developers account, maybe there is an issue. Did you follow guide on their site?  There are few additional steps required to get production ads. https://developers.facebook.com/docs/audience-network/testing

**Comment by perrosnk** [comment]
@sajjanbalar I am facing the same problem. The ads do appear in iOS production, and android developement, but not on android production app. Have you found any solution?

**Comment by sajjanbalar** [comment]
Hi @perrosnk, I couldn't solve the issue with Native Ads. I am using Banner ads for now as they are working on both dev and prod.

**Comment by perrosnk** [comment]
@Trancever Any other ideas? It seems the app is not making a request to FB for an ad. I have used Ad request debugger on Monetization Manager on fb, but it seems there is no call coming from the app. It works on fine on iOS though. 

I have tested both on emulator and real device running Android

**Comment by azisuazusa** [comment]
hello guys, have you solved this issue? I have the same problem

**Comment by perrosnk** [comment]
I think I found the solution! There is this [commit](https://github.com/callstack/react-native-fbads/commit/3ebb23fe4e6996817b7c640671fb7313b00a8b09) that has not been released yet. 
So after mannually changing this [line](https://github.com/callstack/react-native-fbads/blob/3ebb23fe4e6996817b7c640671fb7313b00a8b09/src/android/src/main/java/io/callstack/react/fbads/AdSettingsManager.java#L35) it works on android as well. Hope it works for you as well!

**Comment by Trancever** [comment]
@perrosnk Thanks for spotting this. I'll try to release new minor version this week.

**Comment by azisuazusa** [comment]
@perrosnk Ad Request Debugger still not respond to my request, can I know why this [changes](https://github.com/callstack/react-native-fbads/commit/3ebb23fe4e6996817b7c640671fb7313b00a8b09) work for you?

**Comment by perrosnk** [comment]
@sajjanbalar Are you testing on a REAL device with the FB app installed and logged in with the manager account of FB?

**Comment by perrosnk** [comment]
@azisuazusa By the way I had 

1. modified the app's `build.gradle` file:

- Modified to use this version:
`
    compile('com.facebook.android:audience-network-sdk:4.28.2') {
        exclude group: "com.google.android.gms"  //exclude gms
    }
`

- Added this package:

`
compile('com.android.support:recyclerview-v7:25.3.1') {
  exclude group: "com.google.android.gms"  //exclude gms
}
`
  
  
  
2. And also modified the `react-native-fbads` `build.gradle` file:

`
compile ('com.facebook.android:audience-network-sdk:4.28.2'){ //change version
   exclude group:"com.google.android.gms"  //exclude gms
}
`

The ads weren't working on android after making those changes, but started working when I made the [change](https://github.com/callstack/react-native-fbads/issues/99#issuecomment-400338824) I told you

**Comment by leo7r** [comment]
I have the same issue here, any solution?

**Comment by erandagan** [comment]
Closing this issue as it refers to an old version of this package. If you're still having trouble after upgrading, please open a new issue.
